### ISSUE TITLE
Mayflash GC Controller Adapter not working with m64p

### ISSUE THREAD

**Issue by Turaltay** [simple64/simple64#164]
I am using [this](https://www.amazon.de/gp/product/B00RSXRLUE/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1) Mayflash GC Controller Adapter to play my games with my emulators. Unfortunately it doesn't work properly with m64p. These are the problems i have:

- Sometimes the adapter hinders the emulator to start. Only unplugging the adapter helps. I need to restart my PC to use it again with m64p.
- I get a error sometimes (see attached image)
![2](https://user-images.githubusercontent.com/39458480/120152355-ab488a80-c1ed-11eb-962f-0f881d3ce08d.png)
- Not all C-Buttons can be mapped (see attached image). The left axis works. The right axis is shown as Button 4 and the Up and Down axis can't be mapped. Mapping my Switch Pro Controller works without problems.
![1](https://user-images.githubusercontent.com/39458480/120152686-11351200-c1ee-11eb-9487-f23e9e7d202a.png)
- This adapter supports up to four players. I can't map player 2-4 because the emulator uses the same input as player 1.

These emulators work fine with my adapter:
- MedGui Reborn
- mGBA
- DeSmuME
- Mesen
- bsnes
- Project64
- Dolphin
- Cemu

**Comment by loganmc10** [comment]
I'm curious, what does the name of the controller show as? Can you take a screenshot of the dropdown on the screen that lets you assign controllers to players?

**Comment by Turaltay** [comment]
This adapter seems to have a Pokken Tournament mode, which is mentioned here.  [https://www.mayflash.com/Products/NINTENDOWiiU/W012.html](url). It has a switch on the back for Wii U and PC. The emulator only boots if the adapter is in the Pokken Tournament mode. If i switch from PC to Wii U and back again i can see the normal mode in the device manager. This prevents the emulator from booting. It seems like that the adapter is not even listed in the emulator while beeing in Pokken Tournament mode.
![1](https://user-images.githubusercontent.com/39458480/120277089-deede800-c2b3-11eb-9aaf-fc2592730f6d.png)

**Comment by Turaltay** [comment]
This is the standard mode. The emulator is not starting while the adapter is in this mode.
![1](https://user-images.githubusercontent.com/39458480/120278116-29bc2f80-c2b5-11eb-9038-4f46f69da15c.png)

This is the Pokken Tournament mode. The emulator starts and some buttons can be assigned (as already mentioned above). Only one controller can be assigned.
![2](https://user-images.githubusercontent.com/39458480/120278222-4e180c00-c2b5-11eb-89a0-acf8e6502de6.png)

**Comment by Turaltay** [comment]
I was finally able to map my controller with all buttons: 
![1](https://user-images.githubusercontent.com/39458480/121582651-8c3cca80-ca2f-11eb-8831-62117113f636.png)
The adapter is listed in the drop down menu:
![2](https://user-images.githubusercontent.com/39458480/121582698-9c54aa00-ca2f-11eb-801f-4a7f42bd3bb3.png)

Unfortunately i have some weird behavior after starting a game. The example game is Mario Kart 64.
I can start the game and press the start button. I can move the analog stick between the different game modes (1P Game or 4P Game). I can choose between the different GPs. This is there it starts to act weird. The B button is not responding while i am in this menu.
![3](https://user-images.githubusercontent.com/39458480/121582973-fa818d00-ca2f-11eb-835c-6f35c96ebc17.png)
I can only press A and go into the character menu. This is there the emulator completely stops to detect my inputs. Restarting the emulator leads to the same result.

**Comment by DarthSidious666** [comment]
Is this still happening with the latest build?

**Comment by DarthSidious666** [comment]
Closing due to no response.
