### ISSUE TITLE
Auto-Updater on startup doesnt work, it crashs the program

### ISSUE THREAD

**Issue by rrrcabral** [simple64/simple64#219]
i have the v2021.10.27 version, and today when i've opened the emulator appears the alert of a new version,
when i click YES to update, he says 'downloading updater' and after 1 second... emulator closes.
i've tried 4 ou 5 five times again, always same close.
the only when to enter the emulator is chosing "No" for the alert of new version.

windows 10, nvidia gtx 960, cpu amd ryzen 5 1600AF.

**Comment by DarthSidious666** [comment]
Is this still an issue?

**Comment by zant0** [comment]
As with the latest update the Updates is broken. (build: fbf2c19 Win 10 64bit)  It finishes but the icon is missing and the program name is simple64 build 0b83c2b. You close and the app and open it again and it is back to the old build and tells you that there is  an update.

**Comment by loganmc10** [comment]
The icon will be fixed in the next release. I think the auto-updater is working, its just that the new exe is called simpl64-gui.exe, you'll need to manually delete the old mupen64plus-gui.exe, or download a fresh copy
