### ISSUE TITLE
Emulator crash in Quest 64

### ISSUE THREAD

**Issue by bhlaab** [simple64/simple64#224]
**Describe the bug**
The emulator freezes when using the rock shower spell to kill the skeleton bat enemies in maze area of the 'blue cave' dungeon. Using the spell to kill other enemies elsewhere doesn't appear to cause a crash but I haven't been able to test that thoroughly. The crash only occurs upon the enemies' death, if the spell does not kill them then no crash occurs.

Changing all available core and plugin settings do not have an effect.

**To Reproduce**
1. With Quest 64 running, load the attached 'Quest64-Crash.state' save state
2. This should load you into a battle with the spell menu up already.
3. Press C-Right to select the Rock Shower spell, then press A to execute it.
4. After a spell animation, the emulator ought to freeze. At least, it does for me.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Nov 4 2021 Build
 - GPU: Nvidia GTX 1080ti

**Additional context**
There is a backup save state within the same area included. Just run around and a battle with these bats should commence.

State Download:
[Quest64-Crash.zip](https://github.com/loganmc10/m64p/files/7561226/Quest64-Crash.zip)
.

**Comment by Meerkov** [comment]
The emulator seems like it's responsive.

To me, it looks like the *game* crashed. My understanding is that Quest64 was a rush-job where they cut half of the features (shops, money, etc) and still managed to end up with a pretty buggy game. That said, I can't easily tell in this emulator whether these are lag frames or not.

**Comment by loganmc10** [comment]
I looked into this a bit. Based on the backtrace, it looks like the issue is almost certainly with Parallel-RDP (graphics plugin), it appears to get stuck in a sort of endless loop.

**Comment by DarthSidious666** [comment]
Does this still happen in Quest 64 with the latest build?
