### ISSUE TITLE
Donkey Kong 64 only plays in a small area

### ISSUE THREAD

**Issue by ualaa1** [simple64/simple64#271]
**Describe the bug**
Donkey Kong 64 screen is too small

**To Reproduce**
Open the game

**Expected behavior**
Game should fill the window

**Screenshots**
![bandicam 2022-07-20 23-05-01-852](https://user-images.githubusercontent.com/68984176/180141617-33cbf1b3-ee3b-4ca8-93e0-8764134ea6ad.png)

**Desktop (please complete the following information):**
Windows 10 Nvidia GTX GE 1650

**Additional context**
Config File: 
[mupen64plus.zip](https://github.com/m64p/m64p/files/9156600/mupen64plus.zip)

**Comment by ualaa1** [comment]
For some reason when I tested at first all the other games ran correct size, but I tested again and now they all have same problem as DK. Even when resizing, it still has same issue

**Comment by loganmc10** [comment]
Do you have multiple monitors?

**Comment by ualaa1** [comment]
No, laptop
Anyways, I actually reinstalled and restrated my computer and games seem to be back to correct size, but I want to test more to be sure.
By the way, I also forgot to mention, when the game is in small and not correct mode, it lags very heavily

**Comment by DarthSidious666** [comment]
Is this still an issue in the current build?
