### ISSUE TITLE
Jet Force Gemini freezes during intro

### ISSUE THREAD

**Issue by DarthSidious666** [simple64/simple64#287]
**Describe the bug**
After the ship passes the second planet it freezes with SP crash and a graphics memory location.
Thanks to Kev4cards for pointing out its an RSP issue.

**To Reproduce**
1. Load Jet Force Gemini, can be (U) or (E)
2. Press Start and Play to begin the game after naming a save
3. After the ship flys past the second planet it will freeze.

**Expected behavior**
Progress to the game.

**Screenshots**
![image](https://user-images.githubusercontent.com/57962477/184607037-c22d169d-0bc9-4d0e-a38c-09889b13b4d7.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10
 - GPU: AMD Red Devil 6800XT

**Additional context**
I've tested this game in Ares as well and it behaves the same way. 
Doesn't happen in Project64.

**Comment by loganmc10** [comment]
Thanks, this was broken by https://github.com/m64p/m64p/commit/38d5f37727d8c51b8d9a1ca2609a5b2919978d3c

**Comment by loganmc10** [comment]
I think this may just be a general timing issue, shortening the RSP timing fixes the problem. I assume that lengthening the CPU timing would also fix the problem. It seems like that game thinks the RSP is taking too long relative to the CPU.

**Comment by DarthSidious666** [comment]
Yeah Kev4Cards confirmed it's an RSP issue.
You could try lengthening the CPU timing and see if it does fix it, ,seems like the CPU isn't waiting long enough for the RSP to finish its task. I think that shortening the RSP timing could cause other issues.

You have a better understanding of it than I do so maybe do some test builds and I'll try them out :)

**Comment by Meerkov** [comment]
Still reproduces on most recent build. 
![image](https://user-images.githubusercontent.com/8139496/215304460-da5fe3c4-1448-4398-8d41-714034599ba3.png)

**Comment by Meerkov** [comment]
1) Load game
2) Change the options menu to Widescreen
3) Hard reset the game
4) The game now crashes on startup
![image](https://user-images.githubusercontent.com/8139496/226499941-dc18bb43-2946-4778-af7a-61f3a9c0eac9.png)

**Comment by loganmc10** [comment]
Appears to be working in v2023.07.3
