### ISSUE TITLE
Regression: Indiana Jones freezes during gameplay

### ISSUE THREAD

**Issue by thekovic** [simple64/simple64#293]
**Describe the bug**
Played the level Tian Shan River on the latest release (fbf2c91) and I as I was going down the gorge towards the bridge with the truck, I noticed some audio corruption (sounds playing that shouldn't). After climbing up the bridge and continuing onwards in the level, the game froze completely.

**To Reproduce**
1. Go to level 3 ("Tian Shian")
2. Play the level as described above (forwards around a wolf, down a gorge, and up a bridge). Estimated play time: 1 minute
3. See error

**Expected behavior**
Playable game

**Screenshots**
![image](https://user-images.githubusercontent.com/72971433/185803696-fa6488eb-cbe0-4346-a4e9-fd20e7d611af.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GPU: GTX 1050Ti

**Comment by thekovic** [comment]
@DarthSidious666 Video footage as requested: https://www.youtube.com/watch?v=Cl05xKi4Q8I

**Comment by DarthSidious666** [comment]
Thanks, referenced into table.

**Comment by loganmc10** [comment]
@thekovic are you able to attach your save file (not savestate) so that I can get to this level?

**Comment by thekovic** [comment]
[indy64_save.zip](https://github.com/m64p/m64p/files/9389912/indy64_save.zip)

**Comment by loganmc10** [comment]
Thanks, I could reproduce it. This is probably related to a recent change I made in the emulated length of graphics tasks (https://github.com/m64p/m64p/blob/fbf2c912a7f2f8bdfd26a686bd679418a0ed3270/mupen64plus-core/src/device/rcp/rsp/rsp_core.c#L349)

This is one of the last places in the code where there is just an arbitrary number (40000). I need to do a bit of research on what can be done to estimate a proper number here. Lowering the number would likely fix Indiana Jones, but it may cause issues in other games.

**Comment by thekovic** [comment]
I tested again on the latest version. There's been a bit of a change. The game gets past the bridge but continue a little forwards along the tracks, turn left around the tree, climb upwards and approach the tower and the game freezes during the cutscene that starts. It freezes the whole application - pressing ESC to shutdown emulation no longer works and you need to kill the process with Task Manager.
