### ISSUE TITLE
Suggestion: Rebrand m64p

### ISSUE THREAD

**Issue by DarthSidious666** [simple64/simple64#296]
I know it's been talked about briefly in the discord and we're starting to get people whom are still confused as to what this emulator is so I think it's probably a good time to think about giving the emulator a rebrand with the name that we discussed.

I'll leave here some logos showing some different styles.
![Simple64_Logo](https://user-images.githubusercontent.com/57962477/187679440-9a509952-a24e-49e6-8445-ff1be3ffe6ff.png)
![Simple64_Logo_1](https://user-images.githubusercontent.com/57962477/187680227-a764bbad-5e3c-4ad8-965b-eb17d7b7c3f6.png)
![Simple64_Logo_2](https://user-images.githubusercontent.com/57962477/187680242-6a6a6911-a282-4d50-bd01-62ca582d8ea2.png)

**Comment by loganmc10** [comment]
My wife is telling me the 1st one looks best, and I tend to trust her judgement on this kind of thing lol, so maybe the 1st one?

**Comment by DarthSidious666** [comment]
Sure, I'll package them up in a zip for you once I've made them.

Tell your wife she has good taste :)
