### ISSUE TITLE
Framerate Options

### ISSUE THREAD

**Issue by SephirothFan** [simple64/simple64#299]
Hello!  I just found this project a few days ago and after using it a little, I wanted to ask if it would be possible to implement some framerate options, in addition to 60FPS.  The output framerate for 240p games is:  59.8261 and 59.94 in 480i games.

Could this be added as an enhancement?

Thanks!

SephirothFan

**Comment by loganmc10** [comment]
Do you have numbers for PAL and MPAL as well? I'd be curious to know why interlaced and non-interlaced video have different refresh rates, and how that affects PAL and MPAL refresh rate calculations as well.

**Comment by SephirothFan** [comment]
I don't have the PAL and MPAL output timings, because I only have access to NTSC stuff, but they can calculated from the VI registers on PAL consoles.

**Comment by DarthSidious666** [comment]
I've just tested Shadowman in Nemu64 in both 240p and 480i and I'm getting the following numbers for the FPS from looking at the VI Register in Memory:

PAL M:
240p - 51.22528
480i - 54.17920

PAL: 
240p - 51.22528
480i - 54.18880

NTSC:
240p - 51.23168
480i - 54.18880

I'm not sure how reliable this is as the VI does fluctuate between 49 to 51 in 240p and 49.9 to 54 in 480i.

**Comment by loganmc10** [comment]
@SephirothFan I guess in general I'm a little skeptical that there is a difference between interlaced and non-interlaced video when it comes to refresh rate. Can you share where you got those numbers from?

**Comment by loganmc10** [comment]
I'd also like to point out, that even if the NTSC refresh rate is corrected to 59.94, the FPS counter is still going to show 60. The FPS counter shows "how many frames were displayed in the last second", so it's going to be an integer.

The only way to get a decimal number would be to take the average over a longer period of time (20 seconds or so), however, then the FPS counter wouldn't do a good job of showing sudden dips in performance, which people may be interested in seeing.

**Comment by DarthSidious666** [comment]
Also an interesting fact is that all (U) games had to work on a PAL-M system due to importing.

5-1 MPAL Compatibility of Software for North American Markets (Required)

Description
North American software must be compatible with both NTSC and MPAL formats.

Reason
Games whose market destination is the US must also work on MPAL systems (Brazil) because these games may be shipped to Brazil.

Quote from here:
https://www.forums.benheck.com/viewtopic.php?t=32332

Which I assume must come from Nintendo's programming manual or something.

So Brazil PAL-M games can be treated as NTSC it's only the color signal that's different which I think all emulators ignore.

But here's the colour frequencies that those standards used:

PAL colour subcarrier frequency is 4.43361875 MHz
NTSC colour subcarrier frequency is 3.579545 MHz
PAL-M colour subcarrier frequency is 3.575611 MHz

Also found from the link above.

**Comment by SephirothFan** [comment]
Hmm, those clock rates don't track from the VI register.  Can you check your numbers again; all the data should be there based on your comments.  I got them from the VI register also.

As for 240p and 480i, the line count is different between those two resolutions:  263 lines per field and 262.5 lines per field.  The pixel clock remains the same between the two because that's programmed into the N64 Hardware.

Having the FPS counter be the same is probably fine, given that the backend properly tracks the output refresh of a real console, especially since the program uses that data to help the end-user.

**Comment by loganmc10** [comment]
> As for 240p and 480i, the line count is different between those two resolutions: 263 lines per field and 262.5 lines per field.

I'll need to see documentation of this somewhere, it doesn't make sense to me. NTSC has 525/2 lines per field. I don't understand why it would make a difference if the video was interlaced or not.

**Comment by SephirothFan** [comment]
https://en.m.wikipedia.org/wiki/480i  This page gives a pretty good explanation of the standard, I think.  The difference is 240p has a vertical offset of 0.5 which is how we get 262.5 and 480i is 263.  240p is a clever video trick that happens to work within the 480i standard.

**Comment by loganmc10** [comment]
I'm going to close this unless there is proper documentation to justify this change (it's not present in the wikipedia article). Please provide documentation showing why 240p should have a refresh rate of 59.8261

**Comment by SephirothFan** [comment]
The exact refresh rate for a standard-spec NTSC 480i signal is (2 * 4500000)/(286 * 525) = 59.9400599. For an NTSC 240p signal, the integer 525 gets changed to 526, resulting in the slightly different refresh rate (2 * 4500000)/(286 * 526) = 59.8261054.

https://en.wikipedia.org/wiki/NTSC

This math can be found at the bottom of the Color Encoding section.

**Comment by loganmc10** [comment]
> For an NTSC 240p signal, the integer 525 gets changed to 526

Please cite an exact source for this, quote the article if you need to, I don't see any reference to this in any of the articles you are linking

**Comment by SephirothFan** [comment]
https://junkerhq.net//xrgb/index.php?title=Optimal_timings

Here's another source.  The number of lines in NTSC is 525 which is comprised of 262.5 interlaced fields, based on the NTSC article.  240p is half of 480i which gives us 262.5 the fields are then vertically offset by 0.5 to give us 263 lines of resolution or 240p which is a progressive resolution.  Then taking the math of the NTSC resolution above, we get a dot clock of 59.82Hz.

**Comment by loganmc10** [comment]
Again, nothing you are saying is referenced in the linked article. Wiki articles and forum posts don't constitute documentation for this sort of thing either.

I will work on getting the timing to 59.94 on NTSC, assuming I can get to that number using a formula based on the values in the VI registers, but I still don't see any evidence to support a difference rate for non-interlaced video.

**Comment by SephirothFan** [comment]
"Progressive scan is used for most CRTs, all LCD computer monitors, and most HDTVs as the display resolutions are progressive by nature. Other CRT-type displays, such as SDTVs, needed to use interlace to achieve full vertical resolution, but could display progressive video at the cost of halving the vertical resolution."

https://en.m.wikipedia.org/wiki/Progressive_scan

But no Wikipedia article is what you want?  You need the official NTSC documentation to show this?  I'll look for it, but I'm just wondering why?

**Comment by loganmc10** [comment]
I'm looking for documentation showing they progressive/non-interlaced video creates an extra line that needs to be displayed (526 vs 525).

Interlaced video shows the odd lines, then the even lines. Progressive video shows them all at once, I'm not sure how progressive video creates 526 lines, when the NTSC standard clearly states there are 525.

**Comment by SephirothFan** [comment]
I think I explained this wrong in the beginning.  240p is half of 480i.  It's not 525, it's 263.  Progressive scan is half of the vertical resolution in the NTSC Standard.

**Comment by loganmc10** [comment]
I think you may actually be right, I just don't like to see information without documentation. But let me clear up a few things that make absolutely no sense:

> 262.5 lines per field

It can't draw half a line. One field has 262 lines and the other has 263, there is an even field and an odd field. So in interlaced mode, it draws the even field 30 times a second and the odd field 30 times a second. This means that it draws 262 lines, then 263.

> the fields are then vertically offset by 0.5

I would love to see documentation for this, again it makes no sense to me how you could offset a vertical line on a CRT TV

I believe it's much more simple. When using progressive video, it simply draws the odd lines twice, rather than alternating between even and odd. Therefore it's 263x2, rather than 262+263

**Comment by Jj0YzL5nvJ** [comment]
Honestly speaking, the situation with `PAL` and `PAL/SECAM` is a **mess**, each country implemented it in the way they could. It's a miracle that it worked outside Europe.
The most serious talks on the subject are in Spanish or Portuguese and are related to conversions of VHS/VCD movies and PSX games (PAL to NTSC) for the pirate market. Most people who owned a PS1 in Latin America didn't use it to play video games, they used it as a cheap alternative to VCD players (porno, anime, movies, etc).
Ironically pirated games converted from PAL to NTSC or from PAL to PAL/SECAM often had better quality than the originals, Sony did a very poor job with the PAL regions in Latin America.
Whatever, my knowledge is merely empirical. To my understanding this is what you really looking for:

https://en.wikipedia.org/wiki/576i
https://en.wikipedia.org/wiki/PAL#PAL_signal_details

**Comment by loganmc10** [comment]
I implemented this here: https://github.com/simple64/simple64/pull/300. You can try the build here: https://github.com/simple64/simple64/actions/runs/2990742306

* If you look in the Emulation log for a 240p NTSC game you'll see: "Core: VI: targeting refresh rate of 59.826"
* Interlaced NTSC games show: "Core: VI: targeting refresh rate of 59.940"
* 240p PAL shows: "Core: VI: targeting refresh rate of 49.920"
* Interlaced PAL shows: "Core: VI: targeting refresh rate of 50.000"

I'm going to leave it in PR state for now while I do a bit more research to make sure this is correct

**Comment by SephirothFan** [comment]
Awesome!  Thanks so much for working on this!  Sorry if it was confusing.  I'll keep an eye out for more information that might be helpful.

**Comment by loganmc10** [comment]
Ok I merged this into the main branch, it will be included in the next release (the debug output in the emulation log is commented out though). I don't expect this will make much of a noticeable difference, we're talking about a difference of about 0.2% in refresh rate, but it should be more accurate to the original console.

**Comment by AeliusSaionji** [comment]
> It can't draw half a line. One field has 262 lines and the other has 263, there is an even field and an odd field. So in interlaced mode, it draws the even field 30 times a second and the odd field 30 times a second. This means that it draws 262 lines, then 263.

The CRT is a simple analog machine. Employing a "half line" is the method by which the scanning beam is offset at the start of the next field.
![image](https://user-images.githubusercontent.com/4342746/188757757-817ccfa7-c234-4672-ae2d-c5420eeae25f.png)
