### ISSUE TITLE
Emulator don't start

### ISSUE THREAD

**Issue by MarbaEdge** [simple64/simple64#308]
Hi, I tried your new version but the emulator don't start...using windows 10 64 bits, Intel Core i5-3470 CPU @ 3.20GHz (4 CPUs), 16 gb Ram, DirectX12. I'm doing something wrong? Just download like you say at your page and double clicked on the executable but nothing happens. It's my pc too old for this emulator? Thanks.

**Comment by loganmc10** [comment]
Please see the wiki: https://github.com/simple64/simple64/wiki/simple64-FAQ#1-what-are-the-requirements-for-simple64

Yes, your CPU is slightly too old, and doesn't support the instruction set used by the emulator

**Comment by MarbaEdge** [comment]
Ok, thanks!!
