### ISSUE TITLE
When the emulator fails silently display a reason.

### ISSUE THREAD

**Issue by DarthSidious666** [simple64/simple64#312]
Because people don't read Readme files or look at Wiki pages I was thinking about how else to tell the user why the application fails.

When the application starts and either fails to display anything, has an immediate shutdown or fails to load a rom display a reason in a messagebox as to why or (open the logfile).

Something like "Your CPU needs to support X instructions. Please check your CPU generation family." Or "Your GPU needs to support Vulkan 1.1"

**Comment by loganmc10** [comment]
I don't think this will be possible for CPUs, if the computer doesn't support AVX2, it won't be able to open the program at all. On Linux, if you ran it from the command line, you'd see a message like "illegal instruction", but I don't know how Windows handles it.

For the GPU, it would probably be possible to have it create a message box

**Comment by DarthSidious666** [comment]
Finding the point where the program looks for the CPU instruction before running I think would be the place to maybe write it to a log file and then open that file before the program shuts down from failure.

I could probably kludge something together if I knew where in the code it begins to poll the CPU instruction set.

**Comment by loganmc10** [comment]
You can give it a try but I can't think of a way to make it work. The entire application is compiled with ```-march=x86-64-v3``` which tells the compiler "feel free to use AVX2 (and other) instructions wherever you want when turning this application into assembly language".

**Comment by DarthSidious666** [comment]
Looks like you can detect what features are available at runtime.
https://stackoverflow.com/questions/14266772/how-do-i-call-cpuid-in-linux/14266932#14266932

That hopefully should help a bit for the bash script anyway.

Also found this for the C++ side: https://github.com/Mysticial/FeatureDetector

**Comment by DarthSidious666** [comment]
I think I might have found a solution (finally).

If you use ```cpuid.h``` it should allow you to find the supported instruction sets and then redirect the output to a msgbox if it's not found so then that tells the user why the program doesn't work, it's likely possible to do the same for Vulkan, but I haven't found that one.

Looks like both Windows and Linux can use this header as well.

**Comment by loganmc10** [comment]
I really can't think of a way to make this possible, I'm going to close as a won't fix
