### ISSUE TITLE
Configure the Hotkeys

### ISSUE THREAD

**Issue by xZabuzax** [simple64/simple64#314]
I use the letter "p" as my "right-trigger" so every time I press it the emulator pauses since the pause button is hardcoded to the letter "p" as well which isn't good at all. Having the option to configure the hotkeys to our liking is important IMHO.

**Comment by Jj0YzL5nvJ** [comment]
**CoreEvents**
`Kbd Mapping Pause = 112`

[p = 112](https://github.com/libsdl-org/SDL-1.2/blob/main/include/SDL_keysym.h#L100)

**Comment by DarthSidious666** [comment]
You can change it in the mupen64plus.cfg file so there's no need to really have it as a config option because it's already there.

Change Pause 112 to 19 to use the PAU key instead.

**Comment by loganmc10** [comment]
Fixed in v2023.07.6
