### ISSUE TITLE
64Doom's HUD behave's erratically

### ISSUE THREAD

**Issue by Greenknight9000** [simple64/simple64#315]
I've been playing the homebrew N64 port of Doom known as 64Doom and it appears the HUD behaves very erratically, with Doomguy's head cycling through sprites every frame and overlapping each other, as does the numbers on the Ammo, Health, Armour sections. I assume this might be due to cycling errors as this reportedly doesn't occur on actual N64's, but I figure it's something to look into
![image](https://user-images.githubusercontent.com/91160044/191538526-8df552b7-6085-4ce0-a75e-a0f1a13b8ab9.png)

**Comment by Greenknight9000** [comment]
If a Rom is needed, I'd be happy to provide in private!

**Comment by loganmc10** [comment]
I can't seem to get it to compile, please contact me on Discord at loganmc10#3257 or logan@bacoosta.com

**Comment by loganmc10** [comment]
I can't reproduce this, I tried DOOM1 and DOOM2
![image](https://user-images.githubusercontent.com/848146/191587307-bea99224-5af1-4bd2-acf3-0fe5340c89bb.png)

HUD looked normal to me

**Comment by loganmc10** [comment]
Something wrong with your ROM, confirmed on my console that it does the same thing there
