### ISSUE TITLE
Gauntlet Legends (PAL) Audio crackles/issues in the intro 

### ISSUE THREAD

**Issue by takeshineale128** [simple64/simple64#327]
**Describe the bug**
Audio crackles in the intro

**To Reproduce**
just play the intro and Audio crackles/issue in the intro

**Expected behavior**
Audio crackles in the intro

**Screenshots**
not needed for this issue Audio crackles/issue in the intro
https://youtu.be/0qldzvIK5Go

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version: 11
 - GPU: Nvidia GeForce GTX 1660 

**Additional context**
audio doesn't crackle on pj64 emulator but does on this emulator

**Comment by DarthSidious666** [comment]
Could you try the latest build? I can't replicate this on build 08e2e8e.

**Comment by Meerkov** [comment]
Tested on 08e2e8e. Unable to reproduce the audio issue.

**Comment by Meerkov** [comment]
The audio crackling is because the user's FPS is dropping to 40 FPS, because their computer isn't powerful enough.

**Comment by takeshineale128** [comment]
my pc is 10th gen intel i5 10500 and gtx 1660 and yes i have 08e2e8e build same issue

**Comment by DarthSidious666** [comment]
Well I think the weakpoint in your system is likely the GTX 1660.
Budget GPU cards can struggle to maintain the required framerates needed and this card is only just suitable for 1080p 60fps gaming.

This particular emulator is quite demanding and although your system passes the minimum, the GPU really needs to be a bit stronger.
