### ISSUE TITLE
Legend of Zelda, The - Ocarina of Time - Master Quest (Europe) is running in 60 fps instead of 50 fps

### ISSUE THREAD

**Issue by RokkumanX** [simple64/simple64#330]
**Describe the bug**
The game is running to fast in simple64, instead of 60 fps it should run in 50 fps
The game runs in 50 fps (normal speed) in Project64, RMG and the standalone version of Mupen64Plus.

Game information:

[1618403427E4344A57833043DB5CE3C3]
GoodName=Legend of Zelda, The - Ocarina of Time - Master Quest (Europe) (GameCube Edition)
CRC=1D4136F3 AF63EEA9

**To Reproduce**
1. Open simple64 (latest version will do)
2. Load Legend of Zelda, The - Ocarina of Time - Master Quest (Europe) (GameCube Edition)
3. 60 fps instead of 50 fps

**Expected behavior**
The game to run in normal speed, 50 fps like all PAL/European games does.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise LTSB 21H2
 - GPU: NVIDIA GTX 1070
 - CPU: Intel Core i7 8700K

**Additional context**
Is this somewhat the intended accurate behavior?

**Comment by loganmc10** [comment]
I would need to know how the ROM actually runs on a PAL N64.

The reason it runs fast on Simple64 is that the game sets the vsync variable to 525 (NTSC).

I suspect that the game might exhibit strange behaviour on a real PAL N64, but I don't have one to test, I only have NTSC.

In this case, Simple64 is trying to emulate a PAL N64, so if the same thing happens on a PAL N64, then yes, Simple64 is doing the right thing.

**Comment by RokkumanX** [comment]
Thank you for your quick response @loganmc10 

I wish I could test this on my PAL N64 but unfortunately I don't own the proper tools to do so and I merely extracted the ROM from the bonus disc that came bundled with Wind Waker all those years ago which have played fine in almost any emulator I have played it in until now.

I'm thinking since simple64 is trying to be as accurate as possible my guess would be the same as yours that simple64 is doing the right thing which is totally fine as I like accuracy.

Do you know of a 50 fps game shark code that would somehow force to run the game in 50 fps?
Since there is need for a Ending Credits Fix I don't see a problem adding another code to the game in the Mupen64Plus.ini file really.

**Comment by RokkumanX** [comment]
@loganmc10 

I think I have made a discovery which made the game work 60 fps properly somehow so hear me out on this.

I changed the pif.pal.rom to pif.pal.rom.bak and then I changed the pif.ntsc.rom to pif.pal.rom and the European version of Master Quest ran at 60 fps without any of the speed and sound issues.

Does this makes any sense to you?

I'm not really complaining as the game runs OK now, but yeah using the NTSC pif file renamed to PAL worked totally fine.

**Comment by RokkumanX** [comment]
Master Quest is a tough one, it's not like any other N64 game but I do believe that if one would put the European version and play it on a PAL N64 then the behavior would somewhat be the same as in simple64.

My guess is that using the pif.ntsc.rom with the European version of Master Quest is the only way to play it somewhat correctly, European or not Master Quest is not like other ROMS, Nintendo made something to it.

The European version might just be NTSC somehow, well I don't know.

I'm closing this for the time being.
