### ISSUE TITLE
Some titles have screen shaking/wobbling

### ISSUE THREAD

**Issue by RokkumanX** [simple64/simple64#331]
**Describe the bug**
When you load Perfect Dark and the game start or if you open the Bomber's Notebook in Majora's Mask the screen shakes/wobbles.

**To Reproduce**
1. Load Perfect Dark
2. As soon as the game starts loading with the logos the screen shakes/wobbles but only then not during regular gameplay

**To Reproduce**
1. Load Majora's Mask
2. Open the Bomber's Notebook
3. The Screen shakes/wobbles

**Expected behavior**
Expected behavior would be the screen not shaking/wobbling during these events.

**Screenshots**
N/A

**Desktop (please complete the following information):**
- OS: Windows 10 Enterprise LTSB 21H2
- GPU: NVIDIA GTX 1070
- CPU: Intel Core i7 8700K
- RAM: 64GB

**Additional context**
Nothing specific but doesn't seem to happen on angrylion-plus-rdp in Mupen64Plus standalone or Project64.

**Comment by loganmc10** [comment]
This is the result of the default deinterlacing mode in Parallel RDP (Bob deinterlacing). If you go into the video settings and select "DeinterlaceWeave", it should go away. However, weave deinterlacing has different artifacts, especially during horizontal movement.

It's not really a bug, it's just that Parallel RDP doesn't have super advanced deinterlacing code

**Comment by RokkumanX** [comment]
Thank you for your answer, I tried your suggestion and it worked to some extent but produced other flickering issues, most noticably on the Perfect Dark logo.

I don't really know why these parts shakes and wobbles when every other game seems just fine.

N64 is really strange.

**Comment by RokkumanX** [comment]
Since it's really not a bug I'll close the issue for the time being.
