### ISSUE TITLE
Previous versions of M64P crash when loading now ?

### ISSUE THREAD

**Issue by kazuya-555** [simple64/simple64#334]
This is with Windows 10 64 bit.

I tried with the June 2nd and May versions, before requiring "newer" CPUs. Is this because the GPU driver is now using Vulkan 1.3 ? I`am sure that even more previous versions of M64P used to be okay though.

Games tried where USA versions of Waverace and Perfect Dark.

**Comment by loganmc10** [comment]
If previous versions worked and are not anymore, it's something to do with your computer. Once a version is released, the code is frozen, there isn't something in the code that could retroactively make it stop working
