### ISSUE TITLE
can't build on Ubuntu < 22.10

### ISSUE THREAD

**Issue by cobalt2727** [simple64/simple64#335]
**Describe the bug**
I'm not sure where

**To Reproduce**
1. be on a system that's not x86_64
2. git clone the source
3. `./build.sh`

**Expected behavior**
a normal build process

**Screenshots**
![image](https://user-images.githubusercontent.com/60624944/209037730-21cd412f-4bf7-404b-9034-86a3bd92f508.png)

**Desktop (please complete the following information):**
The device I'm intending to run this on is a Nvidia Jetson Nano (and/or Nintendo Switch booting Ubuntu), but for what it's worth, here's the specs of the cloud VM I'm using to get the build script working:
```r
                                      ubuntu@ubuntu-switch-4-cores-4-gb
      `-/+++++++++++++++++/-.`        ---------------------------------
   `/syyyyyyyyyyyyyyyyyyyyyyys/.      OS: Ubuntu 18.04.6 LTS aarch64
  :yyyyo/-...............-/oyyyy/     Host: KVM Virtual Machine virt-4.2
 /yyys-                     .oyyy+    Kernel: 5.4.0-1090-oracle
.yyyy`                       `syyy-   Uptime: 7 days, 20 hours, 46 mins
:yyyo                         /yyy/   Packages: 1829 (dpkg), 3 (snap)
.yyyy`                       `syyy-   Shell: bash 4.4.20
 /yyys.                     .oyyyo    Resolution: 1024x768
  /yyyyo:-...............-:oyyyy/`    Terminal: /dev/pts/0
   `/syyyyyyyyyyyyyyyyyyyyyyys+.      CPU: (4)
     `.:/+ooooooooooooooo+/:.`        GPU: Red Hat, Inc. Virtio GPU
                                      Memory: 807MiB / 23997MiB

                                                              

You have 5.9GB of space left!
Your external IP is: 
129.213.136.124
ubuntu@ubuntu-switch-4-cores-4-gb:~/simple64$ 
```
A Raspberry Pi 4b was also tested and had the same results.

**Additional context**
[Looks like](https://github.com/simple64/simple64/search?q=x86-64-v3) the CMakeLists files are at fault here, though I'm not sure how to best refactor these to work across different architectures. I would say it's probably best to get rid of the architecture arguments altogether.

**Comment by danmons** [comment]
Final line there in your screenshot is the answer: 
`cc1: error: unknown value 'x86-64-v3' for -march`

This tells the compiler to build specifically for x86-64-v3 instructions like AVX and AVX2, which for emulation of 3D type devices gives quite the performance boost.  These don't exist on aarch64. 

More here:
* https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels
* https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html
* https://gcc.gnu.org/onlinedocs/gcc/AArch64-Options.html

You could potentially dig through each of the `CMakeLists.txt` files within the various components of the project and either alter or remove the `-march` compiler flags.   Setting it to `native` tells the compiler to guess the best fit.  The RPi4B is an ARM Cortex-A72 (ARMv8-A) CPU, so `-march=armv8-a` might also work. 

Whether that compiles something usable is another question.  I don't know if there's code within the project that expects these instructions available specifically.  

The current official Raspberry Pi OS is based on Debian Bullseye which contains a very old version of Mesa that won't have the right Vulkan version.  You'll likely need to upgrade to Debian Bookworm to get the right Vulkan version (compiling newer Mesa into Bullseye doesn't work, as the DRI/DRM libraries are out of date too), and then from there deal with the RPi4B's very weak GPU performance.

**Comment by danmons** [comment]
I got it to compile on Debian Bookwork on a Raspberry Pi4B.  I changed into the source directory and ran:
`find . -type f -name CMakeLists.txt -exec sed -i 's/x86-64-v3/native/g' {} \;`

Then ran `./build` as normal.  That build currently has Mesa 22.3.1 which is pretty close to latest stable at time of writing, so the Vulkan libraries are all new enough to keep the compile happy.

The build works well enough to launch the main GUI, however the RPi4's V3D device is missing features for it to actually start emulation.   Whether it'll run on some other aarch64 device with a  better GPU, I have no idea. 

Output:
```
[INFO]: Layer count: 3
[INFO]: Found layer: VK_LAYER_PRIMUS_PrimusVK.
[INFO]: Found layer: VK_LAYER_MESA_device_select.
[INFO]: Found layer: VK_LAYER_MESA_overlay.
[INFO]: Enabling instance extension: VK_KHR_surface.
[INFO]: Enabling instance extension: VK_KHR_wayland_surface.
[INFO]: Enabling instance extension: VK_KHR_xcb_surface.
[INFO]: Enabling instance extension: VK_KHR_xlib_surface.
[INFO]: Enabling instance extension: VK_EXT_debug_utils.
[INFO]: Enabling instance extension: VK_KHR_get_surface_capabilities2.
[INFO]: Found Vulkan GPU: V3D 4.2
[INFO]:     API: 1.2.230
[INFO]:     Driver: 22.3.1
[INFO]: Found Vulkan GPU: llvmpipe (LLVM 15.0.6, 128 bits)
[INFO]:     API: 1.3.230
[INFO]:     Driver: 0.0.1
[INFO]: Using Vulkan GPU: V3D 4.2
[INFO]: Enabling device extension: VK_KHR_swapchain.
[INFO]: Enabling device extension: VK_KHR_sampler_mirror_clamp_to_edge.
[INFO]: Enabling device extension: VK_KHR_external_semaphore_fd.
[INFO]: Enabling device extension: VK_KHR_external_memory_fd.
[INFO]: Enabling device extension: VK_KHR_image_format_list.
[INFO]: Enabling device extension: VK_KHR_shader_float_controls.
[INFO]: Enabling device extension: VK_KHR_8bit_storage.
[INFO]: Enabling device extension: VK_KHR_16bit_storage.
[INFO]: Enabling device extension: VK_EXT_host_query_reset.
[INFO]: Enabling device extension: VK_KHR_uniform_buffer_standard_layout.
[INFO]: Enabling device extension: VK_KHR_timeline_semaphore.
[INFO]: Enabling device extension: VK_KHR_performance_query.
[INFO]: Enabling device extension: VK_EXT_memory_budget.
[INFO]: Enabling device extension: VK_KHR_synchronization2.
[INFO]: Enabling device extension: VK_EXT_pipeline_creation_cache_control.
[INFO]: Enabling device extension: VK_KHR_format_feature_flags2.
[INFO]: Current transform is enum 0x1.
[INFO]: Supported transform 0x1: IDENTITY_BIT_KHR.
[INFO]: Swapchain current extent: 640 x 439
[INFO]: Targeting 3 swapchain images.
[INFO]: Created swapchain 640 x 439 (fmt: 44, transform: 1).
[INFO]: Got 3 swapchain images.
[WARN]: VK_EXT_external_memory_host not supported or failed, falling back to a slower path.
[WARN]: Device does not support 8 and 16-bit integer arithmetic support. Falling back to 32-bit arithmetic everywhere.
[INFO]: Current transform is enum 0x1.
[INFO]: Supported transform 0x1: IDENTITY_BIT_KHR.
[INFO]: Swapchain current extent: 640 x 480
[INFO]: Targeting 3 swapchain images.
[INFO]: Created swapchain 640 x 480 (fmt: 44, transform: 1).
[INFO]: Got 3 swapchain images.
[WARN]: Stalled compile (compute, 01f928fed7f8a635): thread 0 - 21000.241 us (mode: sync, success: yes).
[WARN]: Stalled compile (graphics, 9a7968ef0abb4692): thread 0 - 96964.851 us (mode: sync, success: yes).
[WARN]: Stalled compile (graphics, aca0de75129e4ab2): thread 0 - 11228.130 us (mode: sync, success: yes).
[WARN]: Stalled compile (graphics, 7ed7e849c617a4f2): thread 0 - 30268.426 us (mode: sync, success: yes).
[WARN]: Stalled compile (compute, 1ca3a8777027bf37): thread 0 - 1331475.832 us (mode: sync, success: yes).
[WARN]: Stalled compile (compute, 09ccfe6c6f3ecc75): thread 0 - 27397.574 us (mode: fail-on-compile-required, success: no).
```

**Comment by cobalt2727** [comment]
This is probably a result of my weird setup and I'm sure it'll work fine on my rpi since that's running 22.10, but:

```sh
ubuntu@ubuntu-switch-4-cores-4-gb:~/simple64$ CC=gcc-11 CXX=g++-11 ./build.sh 
Interprocedural optimizations enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/simple64/mupen64plus-core/build
ninja: no work to do.
Interprocedural optimizations enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/simple64/simple64-input-raphnetraw/build
ninja: no work to do.
Interprocedural optimizations enabled
CMake Error at CMakeLists.txt:25 (qt_standard_project_setup):
  Unknown CMake command "qt_standard_project_setup".


-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/simple64/simple64-input-qt/build/CMakeFiles/CMakeOutput.log".
See also "/home/ubuntu/simple64/simple64-input-qt/build/CMakeFiles/CMakeError.log".


# okay, maybe I'm missing a dependency...?
ubuntu@ubuntu-switch-4-cores-4-gb:~/simple64$ apt search qt6 | grep -i core

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libqt6core5compat6/bionic,now 6.2.2-5~bionic1 arm64 [installed,automatic]
libqt6core5compat6-dev/bionic,now 6.2.2-5~bionic1 arm64 [installed]
libqt6core6/bionic,now 6.2.2+dfsg-6ubuntu2~bionic2 arm64 [installed,automatic]
  Qt 6 core module
libqt6qmlcore6/bionic,now 6.2.2+dfsg-4ubuntu1~bionic1 arm64 [installed,automatic]
  Qt 6 QML Core library
ubuntu@ubuntu-switch-4-cores-4-gb:~/simple64$ 
# nope, doesn't look like it
```

This is still on 18.04, but I've got QT6, GCC11, and a much newer CMake from different PPAs. Not really sure why I'm getting this error...

**Comment by cobalt2727** [comment]
Found the problem - my PPA only provides QT6.2. the `qt_standard_project_setup` command was added in 6.3...

https://doc.qt.io/qt-6.2/cmake-command-reference.html
https://doc.qt.io/qt-6.3/cmake-command-reference.html

Is this something you could work around or would that be out of scope for the project?

**Comment by loganmc10** [comment]
In this repo I only really worry about being able to provide a flatpak, so I don't plan on modifying the CMake setup to support older versions of Qt, unfortunately.
