### ISSUE TITLE
Cycle Half Count

### ISSUE THREAD

**Issue by Meerkov** [simple64/simple64#336]
https://github.com/simple64/simple64/blob/9856a57541b7f36d0b22c77cc466ec22ab82c724/mupen64plus-core/src/device/r4300/cp0.c#L133

Ok, maybe I'm not quite understanding this code. But this looks weird to me.
```

 if (cycles & 1)
    {
        cp0->half_count ^= 1;
        cycles &= ~1;
    }
    uint32_t count = (cycles / 2) + cp0->half_count;
    cp0_regs[CP0_COUNT_REG] += count;
    *r4300_cp0_cycle_count(cp0) += count;
```

This is weird.
Say you first pass in 1. Cycles gets set to 0, half_count gets set to 1, and then count=1.
So far so good.
Then you pass in 2. half_count is still 1... so now count = 1+1=2.

So even though only 3 half-cycles have occurred, it's counted 3 full cycles.

It seems to me that something like this is what it needs to say
```
uint32_t count = (cycles / 2);
 if (cycles & 1)
    {
        count+= cp0->half_count;
        cp0->half_count ^= 1;
    }
    cp0_regs[CP0_COUNT_REG] += count;
    *r4300_cp0_cycle_count(cp0) += count;
```

Otherwise you are repeatedly counting half_counts from previous calls as full counts on future calls.

**Comment by loganmc10** [comment]
Good catch, you are correct, fixed here:

https://github.com/simple64/mupen64plus-core/commit/d3fba219833c0fc6bbd04a3ab3220f787fb286ba

**Comment by philou-felin** [comment]
End users thank you! 😅
