### ISSUE TITLE
[Updated] Simple64 won't open yet on my old laptop

### ISSUE THREAD

**Issue by MasterNama17083** [simple64/simple64#344]
**Describe the bug**
Hello, Okay so this my previous issue didn't finish info enough. I've made the updated version we got.

**To Reproduce**
1. Go to 'simple64'
2. Click on 'simple64-gui.exe'
3. Scroll down to '(idk)'
4. See error: won't open.

**Expected behavior**
 I'm using my old laptop _(from 2013 brought)_ hp pavilion g4 trying to open the `simple64-gui.exe` file the result will not work.
I have an issue, my old laptop has decent hardware inside (not enough/weak a bit).
It says requires a better CPU or Graphics to run smoothly as possible.

_Oh wait. Well, I have another new (good) dell laptop lol._

**Screenshots**
https://user-images.githubusercontent.com/80534869/213916928-2338f66f-9417-44b0-a115-3acd16e803ec.mp4
watch this video, here's the actual proof.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Windows 10 Pro 64-bit (10.0, Build 19041) (19041.vb_release.191206-1406)
 - GPU: AMD Radeon(TM) HD 6480G

**More Specs (from dxdiag.exe compiled details info):**
```
System Model: HP Pavilion g4 Notebook PC
System Manufacturer: Hewlett-Packard
Operating System: Windows 10 Pro 64-bit (10.0, Build 19041) (19041.vb_release.191206-1406)
BIOS: InsydeH2O Version CCB.03.61.31F.69 (type: BIOS)
Processor: AMD A4-3305M APU with Radeon(TM) HD Graphics (2 CPUs), ~1.9GHz
Memory: 4096MB RAM (4GB RAM)
DirectX Version: DirectX 12

Card name: AMD Radeon(TM) HD 6480G
Manufacturer: Advanced Micro Devices, Inc.
Chip type: AMD Radeon Graphics Processor (0x9649)
DAC type: Internal DAC(400MHz)
Device Type: Full Device (POST)
Current Mode: 1366 x 768 (32 bit) (60Hz)
HDR Support: Not Supported
Display Topology: Internal
Driver Model: WDDM 1.2
```

**Additional context**
Take from CPU-Z's screenshots:
![image](https://user-images.githubusercontent.com/80534869/213917088-f9c3b816-b7d2-4d4a-b04c-1d7ea0b10d7b.png)
(Image 1: CPU Info)

![image](https://user-images.githubusercontent.com/80534869/213917136-4cca5b30-afd3-4133-ab2d-46b506aa661f.png)
(Image 2: Motherboard Info)

![image](https://user-images.githubusercontent.com/80534869/213917161-83fcb0aa-5692-4b8e-826f-90eb45b9f0b8.png)
(Image 3: Memory/RAM Info)

![image](https://user-images.githubusercontent.com/80534869/213917225-c5102f3a-8e1d-4f7c-84f0-5d66b40cbbee.png)
(Image 4: RAM Slots Info)

![image](https://user-images.githubusercontent.com/80534869/213917252-c2d601e1-b4b2-4fa2-b3f9-17f5bdb630f6.png)
(Image 5: GFX Info)

**Comment by loganmc10** [comment]
Hi, as noted in the [FAQ](https://github.com/simple64/simple64/wiki/simple64-FAQ#1-what-are-the-requirements-for-simple64). Your CPU needs to support AVX2 instructions. It isn't listed in your first screenshots (under the Instructions) section, so unfortunately this CPU is not compatible with simple64
