### ISSUE TITLE
Flatpak doesn't work (cannot open file: simple64.svg)

### ISSUE THREAD

**Issue by Ka-hu** [simple64/simple64#346]
**Describe the bug**

`flatpak run io.github.simple64.simple64  ` 

gives error:

```
qt.svg: Cannot open file ':/icons/simple64.svg', because: No such file or directory
qt.svg: Cannot open file ':/icons/simple64.svg', because: No such file or directory
```

**To Reproduce**
1. install the flatpak
2. run it

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - GPU: Nvidia

**Comment by loganmc10** [comment]
Those errors are unrelated/unimportant.

Can you post the output of ```cat /proc/cpuinfo|grep model```?

**Comment by Ka-hu** [comment]
Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz

It's a 4 core CPU. The default mupen64plus package (without the GUI, using GlideN64 plugin) works well on my system.

**Comment by loganmc10** [comment]
Simple64 requires a CPU that supports x86-64-v3 (AVX2) (https://github.com/simple64/simple64/wiki/simple64-FAQ#1-what-are-the-requirements-for-simple64)

Unfortunately, your CPU does not support x86-64-v3/AVX2, which is why the program isn't opening

**Comment by loganmc10** [comment]
If you run:
```
/lib64/ld-linux-x86-64.so.2 --help
```
Or possibly (I'm not sure on Arch):
```
/lib/ld-linux-x86-64.so.2 --help
```

It should print out whether your CPU supports x86-64-v3, but basically only Intel CPUs 4xxx or later support it

**Comment by Ka-hu** [comment]
Thank you, I understand now. Okay, I didn't think about this since it did not give me any error message besides that missing svg file. An error message would be helpful ("_CPU is not supported_" or something like that).
