### ISSUE TITLE
HydroThunder - Freeze after finishing 3rd

### ISSUE THREAD

**Issue by Meerkov** [simple64/simple64#347]
**Describe the bug**
Game freezes after getting 3rd place on Arctic Circle race.

**To Reproduce**
1. Play HydroThunder. Play Lost Isle with Midway and get 4th place. Put your name in the high scores.
2. Play the Arctic Circle race with Midway
3. Come in 3rd place (or better)
4. After the race, the screen goes to black and doesn't recover. The FPS still is fluctuating, implying the game is running, but is unrecoverable.

**Expected behavior**
When you get 3rd place, the game is supposed to reward you with potentially unlocking new levels.

**Desktop (please complete the following information):**
 - OS:windows 10
build fa40a1b

**Additional context**

**Comment by DarthSidious666** [comment]
Can't replicate this on build 08e2e8e.

Could you try the newest build and see if you can replicate it?

**Comment by Meerkov** [comment]
I also was unable to repro on 08e2e8e.
