### ISSUE TITLE
Using a Mayflash SS/PS/N64 to usb adapter

### ISSUE THREAD

**Issue by Alexn64gamer0712** [simple64/simple64#348]
Using a Mayflash SS/PS/N64 to usb adapter with an oem n64 controller, calibrated in windows 11, and selected the adapter on "controller options" BIG input lag that makes impossible to play, tested with Ocarina of Time, on the main menu joystick works fine, but as soon as you press the A button it has like 5 full seconds of delay

**Comment by DarthSidious666** [comment]
Could you try updating the firmware and testing again if you haven't done so?
These adapters usually ship with out-of-date firmware and as such have flaws which may be fixed with an update.

**Comment by Alexn64gamer0712** [comment]
Hi, sorry for the late answer ¡¡  I was able to test it with the last update from Mayflash today, still the same issue

**Comment by loganmc10** [comment]
I'm going to close this as there isn't really anything I can do. Simple64 use SDL2 for controller input, so bugs related to specific controllers should be filed with the SDL2 project.
