### ISSUE TITLE
Sarge's Heros 2 - Black Screen on start campaign

### ISSUE THREAD

**Issue by Meerkov** [simple64/simple64#349]
**Describe the bug**
Game fails to load

**To Reproduce**
1. Go to 'Start Campaign'
2. Press Start

Result:
Black screen, game is frozen.

**Desktop (please complete the following information):**
 - OS: windows 10
 - build 08e2e8e

**Additional context**
Game is unplayable as a result.
Reproduced 2/2 times (100% failure rate)

**Comment by loganmc10** [comment]
I can't reproduce this:
![image](https://user-images.githubusercontent.com/848146/215865767-82628dc7-072c-4542-bd09-6ce849dcf25a.png)

**Comment by Meerkov** [comment]
I'm going to guess my copy is corrupted. I tested a different copy and no longer have this issue.
