### ISSUE TITLE
Conker's Bad Fur Day - Corrupted Graphics

### ISSUE THREAD

**Issue by Meerkov** [simple64/simple64#351]
**Describe the bug**
Start a new game.
Press Start

2/3 times - The game was unresponsible and frozen.
1/3 times, pausing showed corrupted graphics
![image](https://user-images.githubusercontent.com/8139496/216499217-4a353e85-559e-4a1b-90dc-19cdfa264edb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Build 08e2e8e

**Comment by Meerkov** [comment]
![image](https://user-images.githubusercontent.com/8139496/216499587-4b0556ad-1aae-40f6-810e-071cdfd8582c.png)
Image of the game freezing on Conker's face (reproduced 2/3 times)

**Comment by FoxbitDreamtail** [comment]
I have had this issue too, except I am on LM21.1'Vera' and the same issues are occurring and t5his is a very well known set of bugs that have been known for a very long time.

**Comment by loganmc10** [comment]
Appears to be working in v2023.07.3
