### ISSUE TITLE
Grey screen; no diagnostic info

### ISSUE THREAD

**Issue by joshudson** [simple64/simple64#355]
**Describe the bug**

Installed simple64 via flatpak; launched as follows:

$ flatpak run --filesystem=host:ro io.github.simple64.simple64 /tmp/portal.z64 

Get ROM from here: https://github.com/lambertjamesd/portal64/releases/tag/v0.7.0

Got grey screen, no diagnostic.

The application menus are running. Open ROM, browse to /tmp and it only shows me subfolders, not the portal.z64 file that's definitely there.

$ file /tmp/portal.z64 
/tmp/portal.z64: Nintendo 64 ROM image: "                    " (N   , Rev.00)

If I had to guess it's just not recognizing it as a ROM image

**Expected behavior**

Run or error

**Screenshots**
Add screenshots and/or a video to help explain your problem.
These **really** help when trying to find bugs, please include them!

**Desktop (please complete the following information):**

Desktop: Debian Bullseye x64

![grey](https://user-images.githubusercontent.com/16249210/218613549-61b1f15b-01e3-4263-afb8-90e5ffd25a6b.png)

**Comment by loganmc10** [comment]
Is it just this ROM you're having problems with? Or all N64 ROMs?

**Comment by joshudson** [comment]
@loganmc10 : Got a test ROM to find out?

**Comment by DarthSidious666** [comment]
here's a (hopefully helpful) link on how to associate file extensions in Linux:
https://stackoverflow.com/questions/30931/register-file-extensions-mime-types-in-linux

**Comment by loganmc10** [comment]
This is a flatpak issue. Even with the filesystem host option, the /tmp directory is not allowed

See: https://docs.flatpak.org/en/latest/sandbox-permissions.html

(Ctrl+F for "These directories are blacklisted")
