### ISSUE TITLE
Simple64 not opening.

### ISSUE THREAD

**Issue by gvnfc3** [simple64/simple64#356]
**Describe the bug**
Simple64 doesn't open.

**To Reproduce**
1. Download Simple64
2. Extract the ZIP File
3. Run simple64-gui.exe
4. Doesn't open

**Expected behavior**
I expected Simple64 to run normally.

**Screenshots**
Add screenshots and/or a video to help explain your problem.
These **really** help when trying to find bugs, please include them!

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11
 - GPU: Intel HD Graphics 2500

**Additional context**

**Comment by DarthSidious666** [comment]
Run through the FAQ.
https://github.com/simple64/simple64/wiki/simple64-FAQ

**Comment by gvnfc3** [comment]
It seems like my CPU does not support Simple64.
