### ISSUE TITLE
Crash after updating the emulator

### ISSUE THREAD

**Issue by CarlosViniMSouza** [simple64/simple64#357]
**Describe the bug**

Well, I updated the emulator twice, and both times, the emulator had the same defect (see image below). I don't know what the specific problem is, but I know that something is wrong with the new version of the emulator

**To Reproduce**

1. Updated the emulator
2. Try open an rom

**Screenshots**

`As I use 2 monitors, the print captured the 2 screens (on the left the wallpaper, on the right LibreOffice Impress with the print of the error, when I tried to open Paper Mario 64)`

![image](https://user-images.githubusercontent.com/60679101/219826333-c289b4dc-cea7-4f42-95d5-aa11435a80b4.png)

**Desktop (please complete the following information):**

 - OS: Windows 11 Home
 - Version: 22H2
 - GPU: Intel Iris Plus

**Additional context**

I hope that the problem is solved, your emulator is very good! 🙏

**Comment by DarthSidious666** [comment]
Try running through the FAQ, I believe step 16 should solve the issue, also try step 12 and update your drivers.
