### ISSUE TITLE
[Feature Request] widescreen support

### ISSUE THREAD

**Issue by powerpuffboysz** [simple64/simple64#360]
Would it be possible to add a widescreen system for n64 games? I dont mean supporting games with built in widescreen but some method of adding cheats or patches for games that dont have widescreen natively. Or maybe adding compatibility with project64 enhancement files?

**Comment by DarthSidious666** [comment]
Nothing like this is planned but anyone is welcome to add the feature via a Pull Request.

You can also patch the game that requires a widescreen hack yourself which is fairly easy to do and test if it works.

**Comment by loganmc10** [comment]
Hi. This emulator doesn't accept feature requests, only PRs (and bug reports)
