### ISSUE TITLE
Cant Open GUI in Windows

### ISSUE THREAD

**Issue by RealALCoL** [simple64/simple64#361]
Hi everyone

i d/l the simple64.zip for windows, extracted and placed in a folder, then try to open simple64 gui app, and cant open dont open no open, try as admin nothing happens, so is that a normal behavior? wait for kind support

**Comment by Jj0YzL5nvJ** [comment]
Most likely your CPU does not have the minimum requirements. See [simple64 FAQ](https://github.com/simple64/simple64/wiki/simple64-FAQ).
