### ISSUE TITLE
Will not run on Debian Testing: Qt: Session management error || Illegal instruction

### ISSUE THREAD

**Issue by othello777** [simple64/simple64#363]
**Describe the bug**
Upon running, I get the following errors,
When compiling from source: `Illegal instruction`
When installing from Flatpak: a qt error, see more in "To Reproduce"

**To Reproduce**
1. Install Debian Testing on a Sandy Bridge laptop. (possibly)
2a. compile from source
3a. `Illegal instruction`
2b. install flatpak
3b: 
```
Gtk-Message: 10:50:43.613: Failed to load module "xapp-gtk3-module"
Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
qt.svg: Cannot open file ':/icons/simple64.svg', because: No such file or directory
qt.svg: Cannot open file ':/icons/simple64.svg', because: No such file or directory
```
**Expected behavior**
Either the Flatpak or compiling from source should work.

**Desktop (please complete the following information):**
 - OS: Debian Testing (cursed)
 - Version: 12 (bookworm)
 - CPU: Intel Core i7-2640M
 - GPU: Intel HD 3000
 - Laptop Model: Lenovo Thinkpad T520

**Additional context**
Technically this install has been around since 2019, and it used to be ubuntu. so there are several cursed/old things going on in the way of packages. I still wouldnt expect neither to work unless my hardware is unsupported. Thanks for any help you may be able to provide.

**Comment by loganmc10** [comment]
Your hardware is unsupported. Simple64 is configured to compile using x86-64-v3 instructions, which requires an Intel 4xxx CPU or better
