### ISSUE TITLE
Simple64 crashes immediately when loading any rom

### ISSUE THREAD

**Issue by Gambit834** [simple64/simple64#364]
Simple64 crashes immediately when loading any rom.

![Untitled](https://user-images.githubusercontent.com/130725721/232359048-e0d6d0d4-d1d1-41a6-96b0-f639c12a3245.jpg)

 - OS: Windows 10 Home 64-bit
 - Version: 22H2
 - GPU: NVIDIA GeForce RTX 3080

Simple64 version 4ec52c2 is the last version to work on my PC. Every version afterwards gives me the "Using video capture frontend: dummy" text in log before crashing to desktop.

**Comment by loganmc10** [comment]
I've heard this from a few people, can you let me know if you have any of the following running at the same time?
* OBS
* Steam
* bandicam

If so, can you try closing them and let me know if it makes a difference?

**Comment by loganmc10** [comment]
I ask because another user had this issue and resolved it by uninstalling Bandicam. I'd be curious to know if you've got Bandicam installed.

**Comment by Gambit834** [comment]
I uninstalled Bandicam and now the latest version of simple64 works fine. Odd... but I'm glad that worked! Thanks.

**Comment by loganmc10** [comment]
Yes it is odd, but unfortunately, probably nothing I can do about it. I assume it's probably this issue: https://www.bandicam.com/forum/viewtopic.php?t=10096
