### ISSUE TITLE
simple64 not doing anything after opening a rom

### ISSUE THREAD

**Issue by Efnyx** [simple64/simple64#366]
I'd really like to use simple64 as it is the only one with built-in VRU support, but every time I attempt to launch a ROM file, .z64 files, simple64 just remains on the same screen as when the GUI is opened, no change. I've tried this with Donkey Kong 64 (USA), Hey You, Pikachu! (USA), and Mario Party (USA), all of which had the same error, and I've yet to find a ROM that it actually boots. This might be an issue on my end, but I'm not familiar with emulators so I am unaware of how to fix this.

 - OS: Windows 10 Pro
 - Version: 22H2
 - GPU: Intel(R) HD Graphics Family

**Comment by loganmc10** [comment]
Please see the FAQ https://github.com/simple64/simple64/wiki/simple64-FAQ
