### ISSUE TITLE
Zelda Ocarina of time - Shadows

### ISSUE THREAD

**Issue by andercard0** [simple64/simple64#368]
**Description of the bug**
As soon as you wake up in the house if you hop above link's bed you can notice some weird shadows

As follows:

Angle 1
https://streamable.com/0rsfba

Angle 2
https://streamable.com/nuach3

**To Reproduce**
1. Start game
2. Wait for the scene end
3. Move link in bed direction
4. See shadows
5. Go outside see more scenes 
6. Then go back inside with new angle change same shadow thing happen

**Expected behavior**
Link with no flicking shadows.

**Screenshots**
![image](https://user-images.githubusercontent.com/43047877/236009628-7ee47a2e-30c8-4d85-b576-44fa9dc4aefb.png)

![image](https://user-images.githubusercontent.com/43047877/236009691-e07a497b-d5cd-4761-b715-6533ccea38ad.png)

I Hope links from streamable don't expire :p 

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10 - 21H2
 - GPU: AMD RX580 - 8Gb

**Additional context**
Well. I'm really not sure if this is a known issue but I tried to search in open issue and couldn't find anything.
Not check the extensive game list test tho. I'm sorry if there is already. anything, just close this one as a duplicate!

**Comment by loganmc10** [comment]
Have you confirmed that the issue doesn't exist on a real console?

**Comment by andercard0** [comment]
Hi, on Nintendo 64 I do not know. 
But and if that counts/matter, it does not on Wii's virtual console which I do believe it is emulation, right?
In the mean time I'll try to reach someone who have the game in real console to confirm that infor for you if you want to.

Also, changed the title which was totally wrong this is not Majora's Mas but Ocarina of time instead.

**Comment by loganmc10** [comment]
I just checked on my N64 console and it looks exactly like your screenshots. The shadows are imperfect.

It's a testament to how much more accurate this emulator is compared to the wii virtual console :) I'm closing this as it matches the behaviour of the real console.

![PXL_20230507_155307178](https://user-images.githubusercontent.com/848146/236688497-e8476afc-0536-4333-aa24-5194c87d165f.jpg)
![PXL_20230507_155422407](https://user-images.githubusercontent.com/848146/236688503-ebd32b20-2eb7-4d76-acfe-d1b619b35ebb.jpg)

**Comment by andercard0** [comment]
Ah great, thanks anyway!
