### ISSUE TITLE
qt svg cannot open file flatpak

### ISSUE THREAD

**Issue by johnny-mac** [simple64/simple64#370]
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=gui-wrapper.sh io.github.simple64.simple64
qt.svg: Cannot open file ':/icons/simple64.svg', because: No such file or directory
qt.svg: Cannot open file ':/icons/simple64.svg', because: No such file or directory

this is what your flatpak app is doing ^

I tried building from source, but I have no idea how to install it. I built it, but getting it to install??? I don't know, you guys don't provide enough documentation.

Edit: I went into simple64/simple64 and tried to ./simple64-gui but it returns the same error as above. I am using Void Linux MUSL.

**Comment by loganmc10** [comment]
Is there a bug besides the message? The icons appear properly, correct?

**Comment by johnny-mac** [comment]
the icon in the menu is there, but I can't launch the program.

**Comment by loganmc10** [comment]
The 2 issues are unrelated. Usually the program not opening is because your CPU doesn't support AVX2 (x86-64-v3), which is required by simple64

**Comment by johnny-mac** [comment]
It definitely does support AVX2. I managed to get m64py to work to configure controls, and then I had to use mupen64plus-qt to launch the game because m64py is all buggy and flickering. It would be nice if your flatpak app actually worked
