### ISSUE TITLE
flatpak app doesn't work

### ISSUE THREAD

**Issue by johnny-mac** [simple64/simple64#371]
Gtk-Message: 21:02:37.586: Failed to load module "canberra-gtk-module"
qt.svg: Cannot open file ':/icons/simple64.svg', because: No such file or directory
qt.svg: Cannot open file ':/icons/simple64.svg', because: No such file or directory

doesn't work in flatpak on Artix Linux & Void Linux MUSL. Same error.

**Comment by loganmc10** [comment]
What model of CPU do you have? `lscpu` should tell you

**Comment by aheike05** [comment]
Same here, Lubuntu 22.04.02 LTS, system installation through flatpak, Simple64 v2023.04.12 (Stable)

**Comment by loganmc10** [comment]
All of these are because of the same reason: your CPU doesn't support x86-64-v3 instructions (AVX2)

see https://github.com/simple64/simple64/wiki/simple64-FAQ#1-what-are-the-requirements-for-simple64

**Comment by johnny-mac** [comment]
You're wrong, my computer supports v3. Its not even old.

**Comment by Jj0YzL5nvJ** [comment]
> You're wrong, my computer supports v3. Its not even old.

Without the info about your CPU, we can only guess. More than 90% of reported "issues" come from CPUs without `AVX2`.

> Gtk-Message: 21:02:37.586: Failed to load module "canberra-gtk-module"

Then try to install `libcanberra-gtk-module`.
