### ISSUE TITLE
Conker's Bad Fur Day (U) Freezes

### ISSUE THREAD

**Issue by DarthSidious666** [simple64/simple64#374]
As the title, on current build 7989d5c freezes on the 'For Mature Audiences Only'.

Only (U) rom is affected (E) works as it should.

**Comment by loganmc10** [comment]
This is a timing thing, it seems to be affected by this value:

https://github.com/simple64/simple64/blob/4bb5ca5a4fae48c7b9b5899bf6eb16ec01af3983/mupen64plus-core/src/device/rcp/rdp/rdp_core.c#L102

I don't know a good way to estimate it at the moment. Making it smaller can break other games (Tetris 64 for example)

**Comment by DarthSidious666** [comment]
Ah, I did wonder if it might be.
Maybe there's a way to check the sync cycle or something?

dp->sync_duration = cpu.sync or something?
