### ISSUE TITLE
black screen when emulating games

### ISSUE THREAD

**Issue by Exi11** [simple64/simple64#375]
I tried to play some super mario 64, and a modded version, then kirby, then zelda, and nothing, i even tried z64 and n64 and it just stays stuck at 0 FPS and when viewing the log it just stops at "Core: Starting R4300 emulator: Cached Interpreter" pls hep

**Comment by loganmc10** [comment]
It sounds like your graphics card probably doesn't support the needed features (Vulkan 1.1)

It's impossible to help with the information here though (no details about your computer at all).

Feel free to join the Discord to try and get some help there: https://discord.gg/tsR3RtYynZ
