### ISSUE TITLE
Games failing to start in builds from the end of April onward

### ISSUE THREAD

**Issue by GPDP1** [simple64/simple64#377]
Games no longer seem to start in builds starting from about April 28. The last working build for me seems to be this one:
https://github.com/simple64/simple64/actions/runs/4821410435

From there on, the two following Windows builds throw up an error about not being able to find the ParaLLEl-RSP plugin, until this  build:
https://github.com/simple64/simple64/actions/runs/4834235525

That build no longer has the error message, but instead, when I load a game, it just shows a black screen, and the FPS indicator stays at 0. All builds from there on out until the most recent one behave the exact same, as far as I've been able to test.

Interestingly, this isn't confined to simple64. RMG (using ParaLLEl-RDP) and ares also no longer work for me in their most recent builds, exhibiting similar behavior to simple64, while older builds do. Given the fact that I see no one else complaining about such a problem, I thus suspect it may have something to do with changes to ParaLLEl-RDP incorporated by all three projects that are in conflict with my (admittedly old) GPU and drivers, although from my testing, RMG's ParaLLEl-RDP stopped working for me as far back as February's version 0.3.5. In any case, I thought I'd check here before filing an issue upstream with Themaister.

Here are my specs:
 - OS: Windows 10 22H2
 - CPU: Intel Core i7-4710MQ
 - GPU: Nvidia Quadro K1100M using the latest available drivers for it (426.78)

In case you're wondering, simple64's log says nothing useful, but RMG's log does:

> [GFX]   [INFO]    Enabling device extension: VK_KHR_sampler_mirror_clamp_to_edge.
> [GFX]   [INFO]    Enabling device extension: VK_KHR_external_semaphore_win32.
> [GFX]   [INFO]    Enabling device extension: VK_KHR_external_memory_win32.
> [GFX]   [INFO]    Enabling device extension: VK_KHR_draw_indirect_count.
> [GFX]   [INFO]    Enabling device extension: VK_KHR_image_format_list.
> [GFX]   [INFO]    Enabling device extension: VK_KHR_shader_float_controls.
> [GFX]   [INFO]    Enabling device extension: VK_KHR_create_renderpass2.
> [GFX]   [INFO]    Enabling device extension: VK_KHR_8bit_storage.
> [GFX]   [INFO]    Enabling device extension: VK_KHR_16bit_storage.
> [GFX]   [INFO]    Enabling device extension: VK_KHR_shader_float16_int8.
> [GFX]   [INFO]    Enabling device extension: VK_EXT_scalar_block_layout.
> [GFX]   [INFO]    Enabling device extension: VK_EXT_external_memory_host.
> [GFX]   [WARNING] Disabling pipeline cache control.
> [GFX]   [ERROR]   No compatible host pointer types are available.
> [GFX]   [ERROR]   Failed to allocate RDRAM with VK_EXT_external_memory_host.
> [GFX]   [WARNING] VK_EXT_external_memory_host not supported or failed, falling back to a slower path.
> [GFX]   [WARNING] Current NVIDIA driver is known to be slightly faster without 8/16-bit integer arithmetic.

Is there a way to enable a more verbose log in simple64 to see if it throws up a similar message?

EDIT: Well, I dusted off my Ubuntu Linux partition on this same machine and decided to try the simple64 flatpak and see how it fared there. Turns out the latest release works just fine, a little slow, but it works. So this may be a Windows driver issue.

**Comment by loganmc10** [comment]
This is specific to your computer, I have no way to reproduce the issue, or to assist. You can try opening an issue in the parallel RDP repo.

**Comment by GPDP1** [comment]
For what it's worth, whatever the problem was is now fixed as of the latest version. I can successfully launch games now on Windows.
