### ISSUE TITLE
"Mupen64Plus" (empty) folder being created in AppData\Roaming despite setting a custom path.

### ISSUE THREAD

**Issue by orymo32** [simple64/simple64#381]
Hello.

**Describe the bug**
Setting up a new "Input Plugin and Config" path works, but for some reason, Simple64 recreates an (empty) "Mupen64Plus" folder in AppData\Roaming after each Simple64 boot.

**To Reproduce**
Go to menu bar -> Settings -> Input Plugin and Config Path Selection -> (Select a custom path of your choice).

**Expected behavior**
Once a custom path has been set and Simple64 has been restarted, no folder generated by the emulator should be located anywhere other than the path set by the user.

**Desktop**
 - OS: Windows 10 21h2
 - GPU: NVIDIA GeForce 920M

**Additional context**
I am using Simple64 v2023.07.6.
Thank you very much.

**Comment by loganmc10** [comment]
Thanks, this will be fixed in the next release (https://github.com/simple64/simple64-gui/commit/4bfdab794ef4211c79cbab3babc53b348c6bd40f)

**Comment by loganmc10** [comment]
Fixed: https://github.com/simple64/simple64/releases/tag/v2023.08.1
