### ISSUE TITLE
[Feature Request] Customizable Save Data and Save State Directory.

### ISSUE THREAD

**Issue by Coolb22** [simple64/simple64#383]
Hello, I would like to request the possibility to freely configure the path where both normal save files and save states will be saved.
In Windows, Simple64 saves these files automatically in AppData\Roaming\Mupen64Plus\save.

This change will be welcomed by users who wish to make Simple64 a more personalized experience.

Thank you very much for your effort.
![1](https://github.com/simple64/simple64/assets/141624493/67620f8f-74b0-41f9-a010-799dbba45e73)

**Comment by loganmc10** [comment]
This is already possible in the core settings, although I admit it's not very user friendly:
![image](https://github.com/simple64/simple64/assets/848146/1c7bbed2-dca6-4632-8ef7-0bc99be6e193)

Updating SaveStatePath and SaveSRAMPath should do what you want, but you need to copy/paste the path, there is no file browser
