### ISSUE TITLE
[Feature Request] Add support for dark mode on Windows

### ISSUE THREAD

**Issue by Steveneska** [simple64/simple64#387]
**Describe the bug**
Not really a bug per se but using Windows 11 in dark mode, I've noticed that while the Simple64 Updater supports dark mode and follows the theme set by the OS, the Simple64 GUI itself does not. I know it's a stretch to ask for such a (trivial) QoL enhancement, but I hope you could consider adding support for dark theme in the emulator itself.

**To Reproduce**
1. Turn on Windows 11 dark mode.
2. Open Simple64 GUI and update the emulator.
3. Once the updater is downloaded, it will open automatically in dark mode following the OS settings.
4. See error.

**Expected behavior**
Simple64 GUI should follow the theme settings set in the OS. If using Windows light theme, the emulator and updater should use light theme. And if using Windows dark theme, it should switch to dark theme automatically (or through a setting at the user's choice).

**Screenshots**
None at this time.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11 (22H2 Build 22621.2134)
 - GPU: NVIDIA GeForce 3070 Ti Laptop

**Additional context**
None at this time.

**Comment by loganmc10** [comment]
Simple64 uses the Qt6 framework for the GUI. Dark mode works in Linux (with GNOME anyway, it  follows the OS theme).

I don't have a windows 11 machine to test with, so this isn't something I would work on, but I'm open to contributions.

**Comment by Jj0YzL5nvJ** [comment]
Implementation example: mpv-player/mpv#11473
For caution (_Win10 LTSB_): mpv-player/mpv#11613

**Comment by Squall-Leonhart** [comment]
Those links are only relevant to Win32 theming, which is NOT used by Qt6.

**Comment by Steveneska** [comment]
I've looked into the Qt implementation of dark mode in Windows. I can work on a solution to this issue if I have a guide on how to compile Simple64 on Windows

**Comment by Calinou** [comment]
Dark theme seems to be used by the GUI as of https://github.com/simple64/simple64/releases/tag/v2024.06.2:

![image](https://github.com/user-attachments/assets/619f0cc4-8526-4909-800f-3322776380a0)

This is on Windows 11 23H2 with dark mode enabled in the system settings.

**Comment by Steveneska** [comment]
Wow that's awesome! I haven't updated my Simple64 installation in months. Going to do it tonight and report back.
