### ISSUE TITLE
nothing happens when i open the simple64-gui.exe file

### ISSUE THREAD

**Issue by ExGuestCJ** [simple64/simple64#394]
btw im on windows 8.1

**Comment by loganmc10** [comment]
Only Win10+ is supported. This is because Qt6 (the GUI toolkit used) only supports Win10+

**Comment by loganmc10** [comment]
see https://www.qt.io/blog/qt6-development-hosts-and-targets

"Both Windows 7 or 8.x version support will not be available for Qt 6. Microsoft discontinued the support for both Windows versions some time ago, and as a vendor, we can no longer maintain support for these windows versions in Qt 6."

**Comment by ExGuestCJ** [comment]
sorry for the annoyance and i forgot i already "asked" this
