### ISSUE TITLE
Program won't launch after update to v2023.11.01 (Windows)

### ISSUE THREAD

**Issue by Index154** [simple64/simple64#405]
**Describe the bug**
When trying to start the program I get a system error saying that libzstd.dll could not be found. The error appears twice in a row. The program does not launch afterwards.
This started happening after I updated to the new release [v2023.11.01](https://github.com/simple64/simple64/releases/tag/v2023.11.01). I downloaded and tested the previous version again just now and that one still launches fine.

**To Reproduce**
1. Go to the simple64 folder
2. Click on simple64-gui.exe
3. See error

**Expected behavior**
The program opening normally.

**Screenshots**
![image](https://github.com/simple64/simple64/assets/105119758/be62bf64-7a61-49ae-a60f-a1f4068c1160)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10
 - GPU: NVIDIA GeForce RTX 3060

**Comment by loganmc10** [comment]
Thanks for the quick report, fixed: https://github.com/simple64/simple64/releases/tag/v2023.11.02
