### ISSUE TITLE
Problem with emulator!

### ISSUE THREAD

**Issue by MoosecianImmerse** [simple64/simple64#411]
![Capture](https://github.com/simple64/simple64/assets/132798005/0bc1ebcf-dade-4bd4-b7ca-c9c99b71d137)
This is the glitchy screen I get when I use the emulator. How do I fix this?

**Comment by MasterNama17083** [comment]
Same. Previously, I made an issue at #402

**Comment by M100o000** [comment]
#422  is same

**Comment by loganmc10** [comment]
Duplicate of #402
