### ISSUE TITLE
Installing simple64 systemwide as a distro package

### ISSUE THREAD

**Issue by orbea** [simple64/simple64#415]
Would it be possible to support installing simple64 as a distro package?

The issues with this that I currently see are:
* No install target for any of the plugins, they should follow [GNUInstallDirs](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html).
* The simple64-gui seems to depend on the plugins being the in same directory as the gui.

For example a package could look like:
```
${CMAKE_INSTALL_BINDIR}/simple-gui
$(CMAKE_INSTALL_LIBDIR}/simple64/libmupen64plus.so
$(CMAKE_INSTALL_DATADIR}/simple64/mupen64plus.ini
....
```

**Comment by loganmc10** [comment]
No, only flatpak will be officially supported on Linux

**Comment by orbea** [comment]
Sorry to hear that, I was hoping to add this to the Gentoo repo...
