### ISSUE TITLE
Simple64 Doesnt Open

### ISSUE THREAD

**Issue by UnknownSkid** [simple64/simple64#416]
it doesnt open, i double click on "simple64-gui.exe" and nothing happens, i put the folder in user/appdata/idk (i made it, its for things that arent in any other folder and i dont want to put it on the desktop and i dont know there to put it else) but idk if that helps

**Comment by loganmc10** [comment]
not enough info

**Comment by UnknownSkid** [comment]
> not enough info

What do you mean not enough info, what else am I supposed to say

**Comment by loganmc10** [comment]
Well you must have blanked out the bug report template in order to post this, you can go look at that and fill it out properly (I don't even know what OS you're using)

**Comment by UnknownSkid** [comment]
> Well you must have blanked out the bug report template in order to post this, you can go look at that and fill it out properly (I don't even know what OS you're using)

im just gonna use project64 it looks like it has more features
