### ISSUE TITLE
ROM loading doesn't work

### ISSUE THREAD

**Issue by AnimatorTao** [simple64/simple64#418]
**Describe the bug**
When I load a ROM nothing happens and the screen stays white

**Expected behavior**
I expect the games to start

**Screenshots**
https://files.catbox.moe/ye7omj.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 21H2
 - GPU: Intel HD 4600 

**Additional context**
Not a rom problem since I've tried different sites

**Comment by loganmc10** [comment]
I don't think your GPU supports Vulkan, which is the graphics API used by the emulator (there is no workaround)
