### ISSUE TITLE
Simple64 doesn't seem to work in Linux Mint

### ISSUE THREAD

**Issue by vortexal** [simple64/simple64#419]
**Describe the bug**
It wont start and it just gives an error message when running in the terminal.

**To Reproduce**
1. Download from simple64's app page on Flathub.org using the provided command.
2. Run the "run" command also provided from the same page on Flathub.org
3. App doesn't start and instead just gives an error message.

**Expected behavior**
The app to start.

**Screenshots**
![Screenshot_2024-02-26_00-45-13](https://github.com/simple64/simple64/assets/32095304/15e5c7ab-071f-4ec1-8b2a-bc8a1a83a0a0)

**Desktop (please complete the following information):**
 - OS: Linux Mint Xfce edition
 - Version: 21.3
 - GPU: AMD ATI Radeon R2 Graphics 

**Additional context**
I can't think of anything else to provide but I have no problem adding more if necessary.

**Comment by PseudoFIame** [comment]
I have the same issue. I got rid of the "Qt: Session management error: Could not open network socket" by removing the environment variable `SESSION_MANAGER` (either `export -n SESSION_MANAGER` or `unset SESSION_MANAGER`). However, now executing `flatpak run io.github.simple64.simple64` just does nothing. Weird: `flatpak run io.github.simple64.simple64 -h` returns help messages, but `flatpak run io.github.simple64.simple64 -v` doesn't return a thing.

Please fix!

By the way, I am using version 2024.03.02 (latest stable as of today).

**Comment by vortexal** [comment]
I just realized something, in "version" was I supposed to provide the version of my OS or the version of Simple64? I was using the newest version at the time but it's since been updated and I've forgotten what version I used. I do know that this issue is still present in the current version (2024.05.3), if there is enough interest in fixing it.

**Comment by loganmc10** [comment]
It's likely that your CPU is too old for this application. Is requires a cpu that supports x86-64-v3, which is basically Intel CPUs from 2013 and later or AMD CPUs from 2015 and later.

**Comment by loganmc10** [comment]
You can run this and it should print out if x86-64-v3 is supported on your computer:

```
/lib/ld-linux-x86-64.so.2 --help
```

Or possibly;
```
/lib64/ld-linux-x86-64.so.2 --help
```

**Comment by vortexal** [comment]
Ok, it does look like my CPU doesn't support that. This is what I get:

Subdirectories of glibc-hwcaps directories, in priority order:
  x86-64-v4
  x86-64-v3
  x86-64-v2 (supported, searched)
