### ISSUE TITLE
Neplay Command Line(CMD)

### ISSUE THREAD

**Issue by predadorBR** [simple64/simple64#423]
Good afternoon, congratulations on the excellent emulator, I would like to integrate with Null dc for multiplay games, where we play Super Nintendo and PS1 mainly, is there a command that I could use in cmd "simple64-gui.exe -rom "C:\Games\n64 \Mario Kart 64 (USA).z64" -Connect "192.168.1.10" -port 4500

**Comment by loganmc10** [comment]
No, a feature like this does not exist
