### ISSUE TITLE
Not accurate at all! No games load just crash.

### ISSUE THREAD

**Issue by KoghaandSooga** [simple64/simple64#424]
Any game either zipped or unzipped do NOT run it just freezes without error and crashes to desktop

Navigate to game directory and load in your rom of choice.

Rom to boot.

Windows 10 Home. 
This is the only emulator to have outright crash. Ares works until you try to save a game and always loses the save.

**Comment by SilverBlade444** [comment]
I'm having the same problem. every time I try to load up a game or a romhack it just stays dark and then closes with no error message. I even tried downloading older versions and they do the same thing.

**Comment by KoghaandSooga** [comment]
> I'm having the same problem. every time I try to load up a game or a romhack it just stays dark and then closes with no error message. I even tried downloading older versions and they do the same thing.

Glad to know not every Github place is toxic. I have been to some emulator places recently and got toxic behavior at me for asking a simple question that has not been addressed. Why do people think that you have to be a knowledgeable god before even being talked to?

**Comment by KoghaandSooga** [comment]
I think that it's a Windows update messing something up internal which means Simple 64 points to an address that either isn't there anymore or the address is being used by something else. IE Busy signal.

 Now considering even older versions crash. I didn't consider trying an older version but I guess it didn't do any good from what you've said. Glad I didn't go thru THAT mess.
________________________________

**Comment by KoghaandSooga** [comment]
Hence why even old versions don't work as they all point to that bad address.
________________________________

**Comment by yiffthefox** [comment]
For some reason the application crashes when the rom file is loaded in the game directory. Try putting your roms outside the main folder and load it like that. That worked for me

**Comment by KoghaandSooga** [comment]
My roms are part of the No Intro set so they are on a folder of it's own already if that's what your referring too?
________________________________

**Comment by livvydoodlez** [comment]
Having same issue for my roms too

**Comment by loganmc10** [comment]
There is not enough info here for me to troubleshoot the issue (GFX card, cpu, etc)
