### ISSUE TITLE
Feature Request: Add SIMDe Library for easy Hardware Architecture independence

### ISSUE THREAD

**Issue by 0lhi** [simple64/simple64#425]
There have been requests to make simple64 compile on other architectures before:

- PPC: https://github.com/simple64/simple64/issues/194
- AMD: https://github.com/simple64/simple64/issues/337

Both were rejected in favor of the advantages that the x86-64-v3 instructions provide.

The SIMDe (SIMD Everywhere) library may provide a solution that aligns with simple64's priorities.

https://github.com/simd-everywhere/simde

Some key points from their README: 

* "*The SIMDe header-only library provides fast, portable implementations of SIMD intrinsics on hardware which doesn't natively support them*"
* "*There is no performance penalty if the hardware supports the native implementation (e.g., SSE/**AVX runs at full speed on x86**, NEON on ARM, etc.).*"
* "*[I]nstead of forcing you to rewrite everything for each architecture, SIMDe lets you get a port up and running almost effortlessly.*"
* "*There are currently **complete implementations** of the following instruction set extensions: [...] x86 / x86_64 [AVX2](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#Advanced_Vector_Extensions_2)[...]*"
* "*[I]t is important to note that you **do not need two separate versions** (one using SIMDe, the other native). **If the native functions are available SIMDe will use them**, and compilers easily optimize away any overhead from SIMDe*"

Adding this library would significantly increase the accessibility of the emulator while allowing x86-64-v3 to remain the focus of the development team and main beneficiary of performance tweaks.

**Comment by loganmc10** [comment]
This does not really apply to how simple64 uses x86-64-v3. Simple64 is compiled using gcc with a target architecture of x86-64-v3, meaning all the C/C++ code is compiled into x86-64-v3 assembly language, this header library won't work around that.
