### ISSUE TITLE
Allow custom netplay servers

### ISSUE THREAD

**Issue by donicrosby** [simple64/simple64#427]
Instead of having hardcoded netplay servers built into the application, it would be nice to be able to run your own for more privacy or if you want it on your LAN to reduce the ping.

This could either be a menu option that lets you input a custom server IP or hostname in in the GUI or it could be a CLI switch that allows you to pass a custom servers.json that would have the URIs with the correct server.

**Comment by loganmc10** [comment]
This is already there. There is a "custom" option in the server list that allows you to input a hostname or IP address

**Comment by donicrosby** [comment]
Ah I missed that! Thanks!
