### ISSUE TITLE
Can't play paper mario anymore.

### ISSUE THREAD

**Issue by ToonJay** [simple64/simple64#433]
**Describe the bug**
After a certain amount of time, the screen freezes on a stutter.
This only happens visually as the game itself is still running (you can tell from audio cues that the game is still running and responding to inputs).

**To Reproduce**
Just play for not even 1 minute.

**Expected behavior**
To be able to play.

**Screenshots**
https://github.com/simple64/simple64/assets/72530183/f0d35497-d428-4130-b621-0bc43b45afa8

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version: 10
 - GPU: NVIDIA GeForce GTX 970

**Additional context**
Opened simple64, there was a notification of a new update. I went with it and then this happened when trying to play paper mario.

**Comment by ThaCataBoi** [comment]
Same exact thing happened to me when I tried to play BlackPit. Thought it may have been an issue with the mod, but I guess it was an emulator thing.

**Comment by loganmc10** [comment]
Is this working now? The latest update includes a fix for Nvidia cards
