### ISSUE TITLE
Linux KDE netplay  " Could not open ROM "

### ISSUE THREAD

**Issue by Winverd** [simple64/simple64#437]
**Describe the bug**
This only seems to be an issue while using KDE as your desktop environment.
While loading a rom from the create room option of the neplay menu in various kde distros, provides the error "Could not open ROM.".  The emulator has no issue loading roms for single player.

**To Reproduce**
While using KDE Desktop Enviroment.
1. Go to Netplay
2. Click on 'Create Room'
3. Fill details and select desired rom
4.  error " Could not open ROM "

**Screenshots**
![Screenshot_20240618_225658](https://github.com/simple64/simple64/assets/7623174/6125823a-44a0-4766-9481-2ea7e91b7361)

**Desktop (please complete the following information):**
 - OS: EndeavourOS
 - KDE Plasma Version: 6.0.5
 - Qt Version: 6.7.1
 - Kernal Version: 6.9.5-arch1-1 (64-bit)
 - CPU:  Ryzen 7 5800x
 - GPU: Radeon 5500 XT 8GB

**Log Readout**
"GUI Error: couldn't open file"

**Additional context**
The emulator seems to not have any problems loading a rom for netplay in various gnome distros, i tried Ubuntu 24.04 & Fedora 40 Gnome and both worked as expected for netplay. Under Opensuse Tumbleweed KDE, Fedora 40 KDE and Endeavour OS KDE the problem persists " Could not open ROM". Behavior is the same with zipped & Extracted rom.

**Comment by loganmc10** [comment]
How was the emulator installed? Flatpak?

**Comment by Winverd** [comment]
> How was the emulator installed? Flatpak?

Yes

**Comment by loganmc10** [comment]
Does it only happen in the netplay menu or also when you launch a single player game?

**Comment by Winverd** [comment]
> Does it only happen in the netplay menu or also when you launch a single player game?

Only in the netplay menu, single player games work with no issue.

**Comment by Winverd** [comment]
Thank you for you help, works as expected now.
