### ISSUE TITLE
"Bad authentication code" when trying to play netplay

### ISSUE THREAD

**Issue by kimimaru4000** [simple64/simple64#440]
**Describe the bug**
Whenever I try to either create a room or join one, I get a popup message box saying "Bad authentication code". I'm not sure what this means and don't see logs in the console that could help me resolve it. 

**To Reproduce**
1. Go to 'Netplay > Create Room'
2. Set the information, such as room name, ROM path, player name, and one of the existing servers (as of this issue, Paris and US East are the only options aside from Custom).
3. Click 'Create Game'
4. A "Bad authentication code" message pops up.

This is also reproducible with 'Netplay > Join Room'. In this case, "Bad authentication code" pops up each time it tries to connect to a server and it never displays any games in that server even if there would be some.

**Expected behavior**
When creating a netplay room, I expect to be able to create the room.

When joining a netplay server, I expect to be able to see existing games and join them.

**Screenshots**
Add screenshots and/or a video to help explain your problem.
These **really** help when trying to find bugs, please include them!

#### Creating a netplay room
![BadAuthenticationCodeCreate](https://github.com/user-attachments/assets/fcb32ae3-3df4-46b4-a134-99a751968b5c)

#### Joining a netplay room
![BadAuthenticationCodeJoin](https://github.com/user-attachments/assets/9b656319-c5c8-4716-886f-329b86736fe8)

**Desktop (please complete the following information):**
 - OS: EndeavourOS (Linux kernel 6.10.2-arch1-1 64-bit)
 - DE: KDE Plasma 6.1.3, Wayland session
 - Version: N/A (rolling release distro)
 - GPU: NVIDIA GeForce RTX 2060

**Additional context**
- Simple64 was installed with [this AUR package](https://aur.archlinux.org/packages/simple64).
- Someone I was trying to play with was running Windows and this issue didn't exist on their end.

**Comment by loganmc10** [comment]
The AUR package is unofficial. Only the official Linux flatpak (and Windows release) can connect to the official netplay servers.

**Comment by kimimaru4000** [comment]
Hey, thanks for the quick reply! Can I ask why that is? I was hoping to keep the AUR package since it's updated along with the rest of my software.

**Comment by loganmc10** [comment]
Basically just to protect the netplay servers from bots/buggy clients that might make them crash, etc... I have no control over the AUR package.

**Comment by kimimaru4000** [comment]
Thanks for the clarification!
