### ISSUE TITLE
Outdated FAQ on cheats

### ISSUE THREAD

**Issue by Calinou** [simple64/simple64#441]
**Describe the bug**

[The FAQ says there's no interface for cheats](https://github.com/simple64/simple64/wiki/simple64-FAQ#3-how-can-i-use-cheats), but there is:

![image](https://github.com/user-attachments/assets/15f53cef-9707-49fb-9b0e-070e0362b70c)

A game needs to be running for the cheat UI to be functional.

**To Reproduce**
1. Go to the FAQ linked above 🙂 

**Expected behavior**
Change the question to point towards the GUI option (and perhaps link to its data source, https://github.com/simple64/cheat-parser).

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11 23H2
 - GPU: NVIDIA GeForce RTX 4090

**Additional context**
N/A

**Comment by loganmc10** [comment]
Fixed, thanks
