### ISSUE TITLE
Unwanted behavior when turning off cheats

### ISSUE THREAD

**Issue by PerdGateEnjoyer** [simple64/simple64#442]
**Describe the bug**
After using the "Infinite/Health" cheat in Donkey Kong 64 (specifically to have an easier time getting the Golden Banana in DK's section of the igloo in Crystal Caves), I found that turning it off and resetting left me with zero health. This resulted in enemies being able to kill me in one hit. 

**To Reproduce**
1. Load a copy of Donkey Kong 64.
2. Activate the "Infinite/Health" cheat.
3. Save the game (either by collecting a Golden Banana or pressing "SAVE" in the options menu).
4. Deactivate the "Infinite/Health" cheat.
5. Save once again, then close and reload the program.

**Expected behavior**
I feel like what should be done is that, when the cheat is activated, the original value should be saved, so that it can be loaded when the cheat is deactivated instead of setting it to zero.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10
 - GPU: Intel UHD Graphics

**Additional context**
I would also like to know if there are any cheats for altering the player's maximum health, so that I can restore my game to normal.

**Comment by loganmc10** [comment]
This is game specific stuff and essentially unrelated to the emulator. Cheats modify the game, and the results can be unpredictable
