### ISSUE TITLE
Paper mario 64 black screen

### ISSUE THREAD

**Issue by apersonontheinternet283** [simple64/simple64#448]
Everytime i open the paper mario 64 rom, it loads the audio but it displays a black screen

The game worked fine in a older version of simple64 but, as of the recent update, it stopped displaying the screen

 - Windows 11
 - Build: 4f239cb [Newest build as of typing this]
 
Before:

![Captura de pantalla (53)](https://github.com/user-attachments/assets/11a227fd-0530-419f-bd22-fa3eb14c1ae0)

After:
![imagen_2024-08-25_173437635](https://github.com/user-attachments/assets/87a31341-17f8-4c7e-b9d5-b0be4fa84a42)

unfortunately i couldn´t be able to record a video to better understand the problem, but i can confirm that the audio is completely fine, and i tried everything already to fix the screen.

im not sure if this happens to other people with other games, so im not entirely sure if im the only one who has this problem or not.

please fix this, and thank you for your time.

**Comment by loganmc10** [comment]
should be fixed in latest version
