### ISSUE TITLE
Updated to v2024.08.1 and now my computer crashes when trying to run simple64

### ISSUE THREAD

**Issue by YamchaGod** [simple64/simple64#449]
I updated to the new version, and now I am unable to run the emulator without it crashing. I was just using it yesterday and it worked perfectly fine, so I can only assume it's the update.

1. Open Simple64
2. Click on 'File' and 'Open Rom'
3. See error

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11
 - GPU: AMD Radeon (TM) Graphics Ryzen 7000 series

**Comment by YamchaGod** [comment]
> Could you be more specific, what do you mean when you say it "crashes"?

I can open up the emulator, but when I try to run Majora's Mask now my laptop freezes for roughly 30 seconds before the emulator force closes. There's no pop-up of any kind, it just stops working.

**Comment by Kombublo** [comment]
Yeah I've having the same issue aswell with all of my roms just crashing the emulator after installing the update. I came here to see if it wasn't just me.

**Comment by loganmc10** [comment]
> Yeah I've having the same issue aswell with all of my roms just crashing the emulator after installing the update. I came here to see if it wasn't just me.

Also an AMD GPU?

**Comment by Kombublo** [comment]
> > Yeah I've having the same issue aswell with all of my roms just crashing the emulator after installing the update. I came here to see if it wasn't just me.
> 
> Also an AMD GPU?

yep

**Comment by Themaister** [comment]
Which driver version is this? Tried updating? I cannot reproduce with RX 7600 on 24.6.1 in parallel-rdp conformance suite.

**Comment by Themaister** [comment]
What happens if you remove push descriptors?

```
diff --git a/vulkan/context.cpp b/vulkan/context.cpp
index a9a07a2..04a7ee4 100644
--- a/vulkan/context.cpp
+++ b/vulkan/context.cpp
@@ -1421,11 +1421,13 @@ bool Context::create_device(VkPhysicalDevice gpu_, VkSurfaceKHR surface,
                ADD_CHAIN(ext.video_maintenance1_features, VIDEO_MAINTENANCE_1_FEATURES_KHR);
        }

+#if 0
        if (has_extension(VK_KHR_PUSH_DESCRIPTOR_EXTENSION_NAME))
        {
                enabled_extensions.push_back(VK_KHR_PUSH_DESCRIPTOR_EXTENSION_NAME);
                ext.supports_push_descriptor = true;
        }
+#endif

        if (has_extension(VK_EXT_IMAGE_COMPRESSION_CONTROL_EXTENSION_NAME))
        {

```

**Comment by Kombublo** [comment]
> Which driver version is this? Tried updating? I cannot reproduce with RX 7600 on 24.6.1 in parallel-rdp conformance suite.

I just updated it and yeah nothing's changed still crashing the emulator.

**Comment by GadgetGeekUSA** [comment]
I can confirm that the latest release crashes or freezes my system upon trying to launch a game. It seems that in an attempt to fix the RDP issue with NVIDIA GPU's an issue was inadvertently created with AMD GPU's because we all seem to have that in common :)

#Specs
Ryzen 5 2400GE
16GB DDR4 3200Mhz
2nd Gen Vega 11 GPU
Windows 11 22621.3880

**Comment by loganmc10** [comment]
Can you try the build available here? https://github.com/simple64/simple64/actions/runs/10628477501 just say no if it asks to update. I don't have access to my Windows machine for a few days.

This build has the changes suggested by Themaister

**Comment by Kombublo** [comment]
> Can you try the build available here? https://github.com/simple64/simple64/actions/runs/10628477501 just say no if it asks to update. I don't have access to my Windows machine for a few days.
> 
> This build has the changes suggested by Themaister
oh yeah it works with this build. Thank you

**Comment by Themaister** [comment]
Can you please state which AMD driver you're using? I need to know so I can apply an appropriate workaround.

**Comment by GadgetGeekUSA** [comment]
Hello,

Windows Device Manager says I'm using version 31.0.21916.2 but the
Adrenaline software says it's version 24.7.1

Hope that helps 😃

**Comment by Themaister** [comment]
Update parallel-rdp-standalone with workaround for AMD non-RADV drivers. Hopefully that works around the issue.

**Comment by loganmc10** [comment]
https://github.com/simple64/simple64/releases/tag/v2024.09.1

@GadgetGeekUSA @YamchaGod @Kombublo can you please test and let me know if it is fixed?

**Comment by Kombublo** [comment]
> https://github.com/simple64/simple64/releases/tag/v2024.09.1
> 
> @GadgetGeekUSA @YamchaGod @Kombublo can you please test and let me know if it is fixed?

The update fixed the issue on my end thanks ya'll.

**Comment by GadgetGeekUSA** [comment]
Works for me too! Thanks 😊
