### ISSUE TITLE
AUR fails to boot roms, possible wayland protocal issue since flatpak boots.

### ISSUE THREAD

**Issue by ariahiro64** [simple64/simple64#462]
**Describe the bug**
compiling simple64 using the aur fails to boot roms under kde
 (did not test other environments nor x11)

**To Reproduce**
1. Install simple64 from the aur using yay or pkgbuild
2. Run any rom image that works with the official flathub
3. Immediately crashes and the window closes

**Expected behavior**
So much as sound or signs of life when booting up any game

**Screenshots**
Add screenshots and/or a video to help explain your problem.
These **really** help when trying to find bugs, please include them!

**Desktop (please complete the following information):**
 - OS: LINUX
 - Distro: endevouros (arch linux flavor)
 - Version: aur (latest git)
 - CPU: AMD RYZEN 3 3100 4 core 8 threads 3.6 GHZ Desktop
 - GPU: AMD RX 5500 XT 8 GB
 - RAM: 32 GB DDR4
**Additional context**
official flatpak works so it is not a hardware issue 
because of this fact i believe this is  a possible wayland protocal issue

**Comment by loganmc10** [comment]
The aur package is not official, you'll have to contact whoever makes it to ask them to fix it

**Comment by ariahiro64** [comment]
unfortunately i know what the issue was and its not aur just contains scripts to compile it form source
however its still not your bug kinda as it uses an unimplemented wayland protocal outside flatpaks sandbox
i installed labwc that uses wlroots and the aur package works

**Comment by ariahiro64** [comment]
with that said i still would recommend the flatpak as its the most reliable way to get simple64 running however i dont think this is an issue you can fix on your side.
