### ISSUE TITLE
[Question] Building without QT?

### ISSUE THREAD

**Issue by vanfanel** [simple64/simple64#465]
I'm trying to build Simple64 on GNU/Linux, on my own minimal Debian-based distro which has a Wayland compositor (libwc) but does not have the huge QT6 libs installed (they pull legacy X11 dependencies if installed via package manager, and are a general hassle to build).

Is it possible to build Simple64 without QT6? I didn't see any independent **CMakeFile.txt** that allows this, only `build.sh` which tries to build with QT6.

**Comment by loganmc10** [comment]
The application is built on top of Qt, there is no non-Qt version
