### ISSUE TITLE
crash when loading any game

### ISSUE THREAD

**Issue by Triramama** [simple64/simple64#470]
my cpu is i9 9900kf , gpu 3060 on windows 10 pro 22h2 OS 10.0.19045Build 19045 (i disabled updates more than 2 years ago if it matters)
please help all emulators work good on my machine do i need to put bios somewhere or something? games that i have are all .z64 extension

**Comment by loganmc10** [comment]
You probably need to update your GPU drivers

**Comment by Triramama** [comment]
i also read that bandicam can cause it cause crash? wtf how? not even running just being in my system causes crash, i have a portable bandicam man

**Comment by loganmc10** [comment]
So you figured out the cause of the crash?

**Comment by Triramama** [comment]
i figured your moms adress faggot
